### ISSUE TITLE
FileStorage chunk size / Write chunks in batch

### ISSUE THREAD

**Issue by ggrenon** [mbdavid/LiteDB#1089]
Hi,

I have a system in which we acquire data in real time and wish to upload it to FileStorage in real time. Currently, I write to LiteFileStream using a BinaryWriter and write around 64kb per BinaryReader.Write() call. It takes 10s to write 1gb of data that way.

For comparison, it takes less than a secon to write this data to a file.

I think it might be slow because of FileStorage small chunk size (256kb). Is it possible to change FileStorage's chunk size and/or batch write these chunks?

Thank you.

**Comment by mbdavid** [comment]
Hi @ggrenon, this is an internal parameter. You can only change by compiling your own version.

But, I don't know if is this the problem of performance when you compare with direct write on disk. 

First: when you write on LiteDB (v4) datafile must be write twice because journal segment. If you disable journal you will see a big difference.

Also, there are some byte array copies that are made to split you file in chunks and this are much more slow than write direct on disk. This will be revised in v5 when I implement using new Span<T>

**Comment by ggrenon** [comment]
Thank you, I'll have a look at v5 when it's out.
