### ISSUE TITLE
Largest database you've maintained with low latency in LiteDB

### ISSUE THREAD

**Issue by Fires1** [mbdavid/LiteDB#1116]
Looking for information as I'm trying to decide between LiteDB & EF6 SQLite. I had a project with over 16,000 entries within a singular SQLite database. 

LiteDB is described for small applications so I have no idea if it can handle this amount.

**Comment by RussellHaley** [comment]
So for "shits-n-giggles" I decided to take you up on this. I created a small app that has a "Company" class and an "Invoice" class and inserted 16000 companies with 10 invoices each. Using the worst case db.Insert() function the entire thing took between 24 - 26 seconds (hardware is an old Gen3 i7 laptop with an SSD). I also added a second "statistics" collection to the database. It inserted records but the counting didn't work correctly. Regardless, the second insert() every 1 second didn't seem to affect performance at all. The total file size is 23.240 Mb. That seems a little high to me so I imagine there is quite a bit of overhead in the BSON encoding?

I then installed LinqPad 5 and the litedb driver found here: https://github.com/adospace/litedbpad. I opened the db file and a basic AllCompany.Take (1000) runs in about 0.5 to 0.7 seconds. Unfortunately I can't write any queries based on my class properties as I get some sort of bson error, but I'll take that up with Mr. @adospace. Some other tidbits:
- Count() on 16000 records in LinqPad takes about 1.400 seconds
- Take(1000) runs in about 0.5, Take(10000) runs in 0.65 seconds and take 16000 also runs in about 0.626 seconds.

The example is here.
https://gist.github.com/RussellHaley/43d862cb5fb2cd1a1e5e87a14cdebee8

Cheers,
Russ

**Comment by RussellHaley** [comment]
Hi Sam, 

While the file size is something to consider, that is the trade of for convenience. When using a relational database system you will need to *design* a database and map between your OO model and the relational model. You will need to be able to write SQL or use an entity relationship mapper that adds overhead. God help you if your database design changes after you've released the software. I've known two people that started with Entity Framework and ripped it out later because it didn't work for them (they both went back to straight ADO.Net). LiteDB simply ingests the objects as they exist in your application, meaning persistence is transparent to the developer. 

Do not under estimate the amount of time and effort (and the bugs!) that come with an RDBMS. In the age of massive hard drives and super quick SSDs, the size trade off could be worth it for a little database like what you are proposing. 

Good Luck!
Russ

**Comment by Fires1** [comment]
Thank you. I think I'll stick with LiteDB then.
