### ISSUE TITLE
Clarification of threading support in v2.0.0-rc

### ISSUE THREAD

**Issue by DavidsonA** [mbdavid/LiteDB#116]
Hi,

I've found LiteDB to be a very useful library. Thanks for your work.

I have some questions about threading support in v2.0.0-rc. I am running an aspnet 5 web site and have set up dependency injection to create a new LiteDB instance for each request. I have found that I needed to add lock() statements and .ToList() calls around every LiteDB method or I get occasional exceptions like "Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage' in LiteDB.

How should LiteDB be used in multi threaded scenarios?

**Comment by mbdavid** [comment]
Hi @DavidsonA, LiteDB v2 supports multi threads using same `LiteDatabase` instance or multi instnaces. If you check, all write operations has `lock` commands (for thread safe) and lock datafile (for processes safe).
Can you write unit test to show this error? "Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage' in LiteDB."

I know an issue about use auto generation `int` in `_id` in multi thread enviorment has some problemns as you can see here #73

**Comment by DavidsonA** [comment]
@mbdavid I may be able to put a unit test together depending on available time over the next few days.

In my case, it was actually read operations that were causing the cast exceptions - I suspect if FindAll() is called and enumerated in two threads it may cause threading issues during enumeration. I found LiteDb to be completely stable (10,000 concurrent load test) by replacing thing.FindAll() with:

    lock(globalLock)
    {
        return thing.FindAll().ToList()
    }

I'll try to get back to you with more precise information soon.

**Comment by stevehayles** [comment]
@mbdavid To add to this I have been seeing exactly the same issue with a call to FindAll() whilst carrying out an Insert on another thread.  'Locking' the call to FindAll obviously only works if I do that throughout my code.

It feels slightly wrong but I have completely resolved the issue by wrapping the method in

`public IEnumerable<BsonDocument> Find(string colName, Query query, int skip = 0, int limit = int.MaxValue)`

inside a Transaction.  I offer this more as feedback rather than a suggested fix

**Comment by mbdavid** [comment]
Hi @stevehayles, after think about your issue it's make sense to me. Find operation are not locked because you can have many threads read data without locking but when one thread change, current reading are no more valid.
Maybe changes on how open datafile will fix this. When are only reading data, open as ReadOnly with share mode. But when needs write, open as exclusive mode.

**Comment by stevehayles** [comment]
Hi @mbdavid 

I have tested this using a "ReaderWriterLockSlim" which on paper fits the situation well and allows concurrent read access from multiple threads but requires  exclusive access for  wrtiting.

It works perfectly but the performance overhead vs a simple lock makes it much slower especially when performing any 'find' query as I am using the 'read' lock within the IEnumerable<BsonDocument> Find method of the DbEngine.

I am looking to see if I can lock at a higher level but I am not convinced that this will result in good performance either.

**Comment by stevehayles** [comment]
@mbdavid 

I now have a performant version that allows concurrent read operations but enforces exclusive write operations. 

There was more than one issue here as I was using 'StreamDiskService' which is commented as 'thread safe' but inherently I don't think it is.  This is most easily solved by wrapping the stream in the StreamDiskService constructor 

`_stream = Stream.Synchronized(stream);`

This is a built in class that implements a monitor on all read/write operations.  This was not an issue in most scenarios as the Transaction<T> method had a higher level lock around the entire call but I was still having issues with concurrent reads. This makes the calls to the stream itself thread safe.

I then added a ReadLock and ReadUnlock methods to IDiskService and changed all Lock / Unlock methods in the StreamDiskService to use a ReaderWriterLockSlim.

In the constructor of 'StreamDiskService'

`_readWriteLock = new ReaderWriterLockSlim(LockRecursionPolicy.SupportsRecursion);`

and then the lock / unlock region looks like this

```
        #region Lock/Unlock

        public void ReadLock()
        {
            this.TryExec(() =>
            {
                _readWriteLock.EnterReadLock();
            });
        }

        public void ReadUnlock()
        {
            _readWriteLock.ExitReadLock();
        }

        /// <summary>
        /// Lock stream
        /// </summary>
        public void Lock()
        {
            this.TryExec(() =>
            {
                _readWriteLock.EnterWriteLock();
            });
        }

        /// <summary>
        /// Release lock
        /// </summary>
        public void Unlock()
        {
            _readWriteLock.ExitWriteLock();
        }

        #endregion Lock/Unlock
```

The last and final change was to modify the DbEngine.Find method to wrap the call inside the new ReadLock

```
public IEnumerable<BsonDocument> Find(string colName, Query query, int skip = 0, int limit = int.MaxValue)
        {
            _disk.ReadLock();

            try
            {
                // get my collection page
                var col = this.GetCollectionPage(colName, false);

                // no collection, no documents
                if (col == null) yield break;

                // get nodes from query executor to get all IndexNodes
                var nodes = query.Run(col, _indexer);

                // skip first N nodes
                if (skip > 0) nodes = nodes.Skip(skip);

                // limit in M nodes
                if (limit != int.MaxValue) nodes = nodes.Take(limit);

                // for each document, read data and deserialize as document
                foreach (var node in nodes)
                {
                    var buffer = _data.Read(node.DataBlock);

                    var doc = BsonSerializer.Deserialize(buffer).AsDocument;

                    yield return doc;

                    _cache.CheckPoint();
                }

                if (_cache.HasDirtyPages)
                {
                    // clear all pages in cache
                    _cache.Clear();
                }
            }
            finally
            {
                _disk.ReadUnlock();
            }
        }
```

For me it's working well and I will try and follow with a pull request and updated unit tests.  The changes aren't too big and there is no need to open the database in any particular mode to get read  write access.

On a passing note, I have tried a number of embedded C# document / nosql solutions (Volante, NDatabase, STSdb, Perst, Siaqodb, DBreeze, VelocityDB, BinaryRage etc) and I think you have a really nice API and well architected codebase that has real promise.

I think there is more that can be done with the performance and it still doesn't feel quite as robust as it should but I think once you get everything firmly onto version 2 (including the documentation !) then LiteDB will be the best solution for many scenarios.

Nice work !

**Comment by mbdavid** [comment]
Hi @DavidsonA,

Thanks for this great contribuition. I never seen this ReaderWriterLockSlim class. Can you post a pull request implementing your suggestion? Will be nice!

In v2 I created this IDiskService to abstract disk acess implementation and be possible to has an database in memory or as a resource files inside an assembly. But all my focus was in FileDiskService (most used way) and reserve this Stream more for testing another features using memory database.

From the start of this project (in may/2014) I always try be as fast as possible. But be safe is more important. No one want loose persisted data (everyone hates MS Access because that :). Thats why I waiting more time for this v2 release: be robust enough to be used in production.

**Comment by stevehayles** [comment]
@mbdavid 

I would not want to issue a pull request until I get time to separate out my code and unit test it properly.

I have discovered one potential issue when a insert / update / index transaction is nested inside a IEnumerable<T> Find method (FindAll for instance).  In this situation the same thread starts by 'Read Locking' the stream and then needs to also 'Write Lock' it inside the original lock.

It's possible to lock the the stream using 'EnterUpgradeableReadLock()' which can then by upgraded to a write lock by calling 'EnterWriteLock()'.  This is perfect for this scenario but I am trying to work out how best to implement this.

This pattern looks great but the problem is that only one thread can be in upgradeable mode at any time.  I am testing now with two different options.

One is to add an optional parameter on the 'Find' calls which allow the user to indicate in their code that they want an upgradeable lock in place 

```
foreach (var foo in _db.Collection.Include(x => x.DbRef).FindAll(upgradeableLock: true)
{
     //updating, deleting or indexing foo here will automatically upgrade the read lock
     //to a write one and everything will carry on just fine.  
     
     //Forgetting  'upgradeableLock: true' will result in an exception being thrown 
     //but will not result in a deadlock or race condition
}
```

This works really well but I am not sure I like the changes or method signatures.

It's always hard to make changes to someone else's project; I really don't want to introduce patterns that you don't like or create further issues.  It's one thing fixing an issue for myself and living with the consequences but quite another breaking your code in some other unforeseen way.
