### ISSUE TITLE
Support for multikey indexes would be nice

### ISSUE THREAD

**Issue by gavinbell** [mbdavid/LiteDB#119]
Assuming the following pseudo data is in a collection:

```
{
  _id: 1,
  item: "abc",
  stock: [
    { size: "S", color: "red", quantity: 25 },
    { size: "S", color: "blue", quantity: 10 },
    { size: "M", color: "blue", quantity: 50 }
  ]
}
{
  _id: 2,
  item: "def",
  stock: [
    { size: "S", color: "blue", quantity: 20 },
    { size: "M", color: "blue", quantity: 5 },
    { size: "M", color: "black", quantity: 10 },
    { size: "L", color: "red", quantity: 2 }
  ]
}
{
  _id: 3,
  item: "ijk",
  stock: [
    { size: "M", color: "blue", quantity: 15 },
    { size: "L", color: "blue", quantity: 100 },
    { size: "L", color: "red", quantity: 25 }
  ]
}
```

Where an index is defined on the collection by:
```
collection.EnsureIndex("stock.size");
```

Then querying the collection using:
```
collection.Find( Query.EQ("stock.size", "L"));
```

I would expect the query to return 2 documents {_id=2, _id=3}.

Version v.2.0.0-rc accepts the index definition, adding data to the collection doesn't add any indices for the fields and the query returns 0 documents.

**Comment by mbdavid** [comment]
Hi @gavinbell, I have plans, in  future, implement some of this indexes like mongodb do (multikey and compound indexes). With my index implementation, compound indexes are simple do implement but a little be complex to query (need a real query engine do choice with each index use).
But multikey is much more complex because current data/index pages doesn't support this 1 document = N indexes values. Maybe future versions with another data structure conecpts or some high level implementation (with auxiliar collection to store `_id` and index key values, like used in `FileStorage` implementation).

**Comment by shycohen** [comment]
Here's a nice approach to simple-to-complex indexes with a unified approach: https://www.rethinkdb.com/docs/secondary-indexes/javascript/

**Comment by mbdavid** [comment]
Added in New Features issue #20
