### ISSUE TITLE
Order By

### ISSUE THREAD

**Issue by Siegmar** [mbdavid/LiteDB#139]
Hi,
Considering the Code Project article about LINQ, OrderBy should be used like this:

```cs
// WHERE
albumEnumerable = albumCollection
    .Include(x => x.Artist)
    //.Find(x => x.AlbumId > albumId, skip , limit);
    .Find(x => x.AlbumId > albumId);
// ORDER BY
albumEnumerable = albumEnumerable
    .OrderByDescending(x => x.Title)
    .Skip(skip)
    .Take(limit);
```
Consider I have 1.000 Albums and keep 900 after filtering.
If I execute the C# code above I get 900 in my IEnumerable, consuming a lot of memory.
Just after loading all 900 I order them and filter the first 3.

But if I execute the SQL shown below in Entity Framework or NHIbernate I load just 3 records in memory:

```sql
SELECT TOP 3 *
FROM Album
WHERE Album > 20
ORDER BY Title DESC
```

Is there any way to ordering the Collection, before filtering, instead of ordering the IEnumerable ?

**Comment by mbdavid** [comment]
It's a commom mistake, let's undersantand:

LiteDB is an embedded database - no server, no main service running. So, client and server are the same. And worst, each instance of client are an instance of server too.

But when you are in a DBMS enviorment and run this:

```sql
SELECT TOP 3 *
FROM Album
WHERE AlbumId > 20
ORDER BY Title DESC
```

What server (not the client) do? Well,  first will execute WHERE using `AlbumId` index. let's says that query returns 900 rows. After that, DBMS need order this 900 rows using `Title` field. If there is no `Title` index, DBMS will load all 900 records in memory/cache (tables are simple than documents, because all rows has same data structure), order by `Title` and then select first 3 rows. If has an index in `Title`, DBMS will get order from index, and load only 3 records.

Back to LiteDB: Skip/Limit in Query command is useful to avoid deserialize document that you will not use. The order from this skip/limit is based only in what index are used in this Query execution. So, if you do:

```C#
col.Find(x => x.Price > 20)
```

All documents are native ordered by `Price`.

Thats why LiteDB has no OrderBy internal implementation and non-index document field query. Let's LINQ to object do the job with `IEnumerable`.

**Comment by Siegmar** [comment]
Hi,
Thanks for the answer.
Anyway I may use the solution above or the solution below:

```cs
Expression<Func<Album, bool>> where = System.Linq.Dynamic.DynamicExpression.ParseLambda<Album, bool>("AlbumId > @0", albumId);
albumQueryable = albumCollection
    .Include(x => x.Artist)
    .Find(where)
    .AsQueryable();
albumEnumerable = albumQueryable
    .OrderBy("Title descending")
    .Skip(skip)
    .Take(limit)
```
