### ISSUE TITLE
cannot query on strings in v5

### ISSUE THREAD

**Issue by BangL** [mbdavid/LiteDB#1433]
```
System.NotSupportedException: "Method CompareString not available to convert to BsonExpression (CompareString(x.Name, value(testLiteDB.MainWindow+_Closure$__0-0).$VB$Local_customer.Name, False))."
```
how to reproduce:
just perform any kind of query (Query/Find/FindOne) on a string property, using Lambda-Epressions.
works in v4.

**Comment by mbdavid** [comment]
Hi @BangL, can you write this query example? In v5 lambda expressions must be converted into BsonExpression.... in v4, if not possible, LiteDB uses Linq to Objects

**Comment by BangL** [comment]
my example was something like this:
`Dim oldObj As MyClass = Items.FindOne(Function(x) x.Identifier = newObj.Identifier)`
while newObj was of type "MyClass" as well.

i've already migrated to `Items.FindOne($"$._id = '{newObj.Identifier}'")` overload, which solves the problem for me.
but the overload for linq does not work this way.

**Comment by BangL** [comment]
might be a conflict with how VB handles lambda. not sure

**Comment by BangL** [comment]
Stacktrace:
   bei LiteDB.LinqExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   bei System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   bei LiteDB.LinqExpressionVisitor.VisitAsPredicate(Expression expr, Boolean ensurePredicate)
   bei LiteDB.LinqExpressionVisitor.VisitBinary(BinaryExpression node)
   bei System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   bei LiteDB.LinqExpressionVisitor.VisitLambda[T](Expression`1 node)
   bei System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei LiteDB.LinqExpressionVisitor.Resolve(Boolean predicate)
   bei LiteDB.BsonMapper.GetExpression[T,K](Expression`1 predicate)
   bei LiteDB.LiteCollection`1.Find(Expression`1 predicate, Int32 skip, Int32 limit)
   bei testLiteDB.MainWindow..ctor() in C:\Users\BangL\source\repos\testLiteDB\testLiteDB\MainWindow.xaml.vb: Zeile20

**Comment by lbnascimento** [comment]
@BangL In C#, the equality operator is a "real" operator and the BsonMapper successfully converts it to a to an expression. However, in VB, the string equality operator is converted to a call to `CompareString`, and the BsonMapper doesn't know what to do with it.

In previous versions of LiteDB, lambdas that were not sucessfully converted to expressions were stored and executed after the results were retrieved and mapped to object. However, this feature was removed in v5 due to performance issues - if you ran your query on a collection with 1 million entries, all of them would be retrieved before the lambda expression was executed, which is very inefficient.

This feature may be recreated in v5.1 in a more efficient way, however please note that there might be a significant performance hit.

**Comment by BangL** [comment]
very good to know. thanks for the explanation!
for me personally this problem is solved then, i will go BsonExpressions only from now on.

despite the performance issues and the vb.net incompatiblity, i would suggest putting the [DeprecatedAttribute] onto the lambda overloads though.
