### ISSUE TITLE
[QUESTION] What's the equivalent for db.GetCollection<Command>("commands").Include(new string[] { "$.Package", "$.Command", "$.Command.Package" }) in version 5?

### ISSUE THREAD

**Issue by loebi-ch** [mbdavid/LiteDB#1450]
Hi there!

I have migrated LiteDB from version 4 to 5 and face the problem that `Include()` doesnt' accept a string **ARRAY** argument anymore.

So far, I have used
`db.GetCollection<Command>("commands").Include(new string[] { "$.Package", "$.Command", "$.Command.Package" })`

`Command` is an abstract class and there are different implementations of it. I save all of them in one collection. Some of them have DBRefs to other objects, some of them have not. That's the reason why I cannot use

`db.GetCollection<Command>("commands").Include(t => t.Package)`

because the abstract class `Command` does not have a `Package` property.

What's the correct way in version 5 to include the DbRefs (and even nested DBRefs) in this scenario with abstract classes?

Looking forward to your answer. Thank you!

**Comment by lbnascimento** [comment]
@loebi-ch There's an onverload of `Include` that takes a `BsonExpression` as argument, and strings are implicitly converted to `BsonExpression`, so you can simply use `db.GetCollection<Command>("commands").Include("$.Package")` for your first include. This should work for abstract classes with no issues, even if some of the subclasses don't have a `Package` property.

Regarding the rest of your question, could you post your classes (or a simplified version of them) and some usage? If `$.Command` is a reference from an instance of `Command` to another, it won't work because LiteDB does not support circular references (in fact, it should not work in v4 too).

**Comment by loebi-ch** [comment]
Thank you @lbnascimento for your very fast response.

I wrote "I have migrated LiteDB from version 4 to 5 and face the problem that Include() doesn't accept a string argument anymore." Actually I meant "STRING ARRAY".

So before in version 4 I used a string array like this:

`db.GetCollection<Command>("commands").Include(new string[] { "$.Package", "$.Command", "$.Command.Package" })`

Does the correct new approach in version 5 looks like this:

`db.GetCollection<Command>("commands").Include("$.Package, $.Command, $.Command.Package")`

A string instead of a string array? And can I just comma separate it, or do I have to use multiple includes like

`db.GetCollection<Command>("commands").Include("$.Package").Include("$.Command").Include("$.Command.Package")`

Actually there is no rest in my question... but I see your confusion because in my example I have used `$.Command` in db.GetCollection<Command>("commands")... but forget about this, there are no circular references and I understood that this is not supported.

**Comment by lbnascimento** [comment]
@loebi-ch You have to make multiple calls to `Include`, in the same order that you used to place the expressions in the string array. So yes, it would look something like `db.GetCollection<Command>("commands").Include("$.Package").Include("$.Command").Include("$.Command.Package")`.

We are considering creating a new overload to `Include` that takes a `params BsonExpression[]` as input in the next incremental release.

**Comment by loebi-ch** [comment]
Thank you!
