### ISSUE TITLE
[QUESTION]"Part URI cannot start with two forward slashes " occurs when v4 to v5

### ISSUE THREAD

**Issue by GitOffice** [mbdavid/LiteDB#1459]
Install-Package LiteDB -Version 4.1.4 is OK, but it is not for  Version 5.0.1
![73990223-7f175380-4983-11ea-8af2-b2350428e025](https://user-images.githubusercontent.com/1814649/74103197-28796780-4b85-11ea-8a46-ab8d6f19d84b.png)

**Comment by mbdavid** [comment]
Is this error occurs only with LiteDB? I try reproduce here but has no problem (and there is no more issues about this).

**Comment by JensSchadron** [comment]
While I can't reproduce this issue myself, I'm going to investigate this a bit more.

**Comment by JensSchadron** [comment]
I think I might have a possible solution for this issue.
As per [this response](https://github.com/NuGet/Home/issues/7601#issuecomment-502813859), I might be able to resolve it by leaving the PackagePath attribute for the License file empty in the csproj file.
Another solution would be to give the license file an extension  (.txt or .md) as per [this link](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#license)

@GitOffice I also noticed that you're using a pretty old version of the Package Manager Console Host (v2.12.0.817). I, myself, am on v5.4.0.6292 so that might explain why both David and I can't reproduce your issue :)

**Comment by mbdavid** [comment]
Wow, @JensSchadron can be right. v5 has update 2 tags: License e Icon as recommended nuget upload package

**Comment by JensSchadron** [comment]
@GitOffice So a new version (5.0.3) will be released somewhere next week as stated in #1466.
Please let us know if the fix I did actually works :) If not, I'll try fixing it the other way. So, best case, you can install LiteDB next week, worst case in 2 weeks from now.

**Comment by GitOffice** [comment]
Got it.Thanks.

**Comment by JensSchadron** [comment]
@GitOffice 5.0.3 just got released today, could you please let me know if you could install this version?

**Comment by GitOffice** [comment]
Thanks, It works and saves my tons of time.
