### ISSUE TITLE
This database exceeded the maximum limit of collection names size: 3000 bytes

### ISSUE THREAD

**Issue by Shirim78** [mbdavid/LiteDB#151]
Hi,

Thanks for coming with such a great software.

I have encountered this error "This database exceeded the maximum limit of collection names size: 3000 bytes".

Is there any way this limit can be increased further?
Thanks!

**Comment by mbdavid** [comment]
Hi @Shirim78, LiteDB store collection names in Header Page. Pages has 4096 bytes, so I limit use in 3000 bytes all collections names. To change this, I need change pages to 8192 bytes witch is not a good performance as I tested.

I recommend you to use shorter names or declare CONST variables:

`const string USERS_COLLECTION = "usr";`
`const string CUSTOMERS_COLLECTION = "ctm";`

**Comment by mciureanu** [comment]
I receive the same exception after a few successful inserts, as if the name gets bigger with each insert or something...

**Comment by kieferm** [comment]
Hi @mbdavid ,

I am also running into the same issue described above.  In my testing I have found that even with very short collection names (`01`, `02`, `03`...) plus 8 bytes for string length and uint page ID the maximum number of collections is around 300.  Is that number correct?  Do you have any recommendations for storing a larger number of unique data sets?

Thanks.

**Comment by mbdavid** [comment]
Hi @kieferm, if you need more than 300 collection I recommend you try to split into more files if it´s possible. 
Early versions of LiteDB (1 and 2) support was limited in 256 collection but it´s only a "magic" number and can be removed because they dont use header page to store collections names/pointers. All collections names are stored into a linked page list. But, there is no index to find a collection (use full search), so if you have 5000 collection in a single datafile, litedb must load 5000 pages just to reach your last page.
