### ISSUE TITLE
Index length limit

### ISSUE THREAD

**Issue by mitja-p** [mbdavid/LiteDB#1525]
It says: _Index values must have less than 512 bytes (after BSON serialization)._

Questions:
I get this exception: LiteDB.LiteException: 'Index key must be less than 255 bytes.' Which is correct?
When index is multikey index, should this limit apply to individual element or whole multikey? Multikey  ['a','b','c'] has length 3 or 1 as each is 1 byte?

**Comment by lbnascimento** [comment]
@mitja-p The correct value is 255 (the lenght of the index key must fit in a byte). I will fix the documentation.

Regarding your question, your example `["a", "b", "c"]` takes 32 bytes after BSON serialization. This is because it is stored as the following document: `{"0": "a", "1":"b", "2":"c"}`. Each element takes 9 bytes  (2 bytes for the key string, 2 bytes for the value string (because of the trailing `\0`) and a 5-byte overhead because string is a variable-length type) and there's also another 5-byte overhead for the document itself, adding up to 32 bytes.

If this answers your question, please close the issue.
