### ISSUE TITLE
[QUESTION] Getting raw data using Include changed from 5.0.5 to 5.0.7. Is it OK?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1632]
Getting raw data using Include changed from 5.0.5 to 5.0.7. Is it OK?

In the scenario described below result data in 5.0.7 are different from 5.0.5.
I would like to check if the change is intended.

```csharp
class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
}
class Order
{
    public int Id { get; set; }
    [BsonRef("customers")]
    public Customer Customer { get; set; }
}
[Fact]
public void Include_Get_Raw()
{
    var customer1 = new Customer() { Id = 1, Name = "Joe" };
    var order1 = new Order() { Id = 1, Customer = customer1 };
    using var db = new LiteDatabase(":memory:");
    var customers = db.GetCollection<Customer>("customers");
    var orders = db.GetCollection<Order>("orders");
    customers.Insert(customer1);
    orders.Insert(order1);

    var rawOrders = db.GetCollection("orders");
    var doc = rawOrders.Include("Customer").FindById(1);
    var r = JsonSerializer.Serialize(doc);
    System.Diagnostics.Debug.Write(r);
    Assert.Equal("{\"_id\":1,\"Customer\":{\"$id\":1,\"Name\":\"Joe\"}}", r);
}
```

The above test returns the included document embedded as expected.
But it contains some strange `$id` field in 5.0.7.
In 5.0.5 this field is `_id` (rather expected).
Is this change intended?

The same is true for a collection of referenced objects.
In 5.0.5 they are expanded to a list of raw documents with `_id`.
In 5.0.7 they contain `$id`.

**Comment by lbnascimento** [comment]
@nightroman This is intentional. It is intended as a fix to #1625. When querying using Linq, an expression like `col.Find(order => order.Customer.Id == 1)` would be converted to the BsonExpression `$.Customer.$id = 1`, which meant that Linq queries over the id of a referred document would not work if the `Include` had been processed (it would work without the `Include`, though).

The ideal solution would've been to make the Linq-to-BsonExpression mapper aware of the existence or inexistence of an include, but that seemed really hard without major changes, so we decided to change the deserialization format. This does not alter the datafile in any way.

**Comment by nightroman** [comment]
Thank you. It's a potentially incompatible change for applications. It might be useful to mention this in https://github.com/mbdavid/LiteDB/releases/tag/v5.0.7

**Comment by lbnascimento** [comment]
@nightroman Thanks, added it to the release info.
