### ISSUE TITLE
[BUG] System.Reflection.AmbiguousMatchException after fix #1625

### ISSUE THREAD

**Issue by fu-hsi** [mbdavid/LiteDB#1634]
When I add new product, listing the products generate Exception:
`An` unhandled exception of type 'System.Reflection.AmbiguousMatchException' occurred in mscorlib.dll

For sure, I removed all records before:
```
db.GetCollection<Product>("products").DeleteAll();
db.GetCollection<Category>("categories").DeleteAll();
```

First exception I was received after product update.

List:
```
var result = db.GetCollection<Product>("products").FindAll().ToList();
```

**Comment by fu-hsi** [comment]
I found the line, that generate Exception in Product class:

```
public NameValueCollection Features { get; set; } = new NameValueCollection();
```

**Comment by lbnascimento** [comment]
@fu-hsi `NameValueCollection` does not implement `IEnumerable<KeyValuePair<TKey, TValue>>` or anything similar, which means our mapper does not serialize it correctly (it only serializes the keys). So, unless you really need to work with duplicate keys, I suggest you stick to `Dictionary<string, string>`.

I may add a fix for this later, it isn't very difficult, but I'll have to explicitly test for `NameValueCollection` because it doesn't implement `IEnumerable<KeyValuePair<TKey, TValue>>`.

**Comment by fu-hsi** [comment]
As I mentioned, I will use Dictionary<string, string>, but if NameValueCollection doesn't work, maybe it is better to remove them from BsonMapper table https://github.com/mbdavid/LiteDB/wiki/Object-Mapping? Maybe I misinterpreted it, if so, sorry for the confusion. It's not important to me, I will use Dictionary.

**Comment by lbnascimento** [comment]
@fu-hsi Just a tip: the documentation in our wiki is for LiteDB v4. For v5 docs, check [our web page](http://www.litedb.org/). But you are correct, I will remove the class from our documentation.
