### ISSUE TITLE
[QUESTION] How to use the GROUP BY with HAVING in LiteDB v5

### ISSUE THREAD

**Issue by eschlot** [mbdavid/LiteDB#1739]
I want to do a database request using GROUP BY clause like follows:

`SELECT $, SHA, count(*) c FROM picturedata GROUP BY SHA HAVING @c > 1;`

The result is "no result" even though I have datasets which have the same String for the attribute SHA.
The desired output is an array of all objects in the picturedata collection having a value for SHA that is repeated.

I am not able to figure out from any documentation on the internet on how to write a valid clause with GROUP BY and also not with GROUP BY and HAVING together. 

Can anybody post an example on using and building a right syntax for this type of request? That would really help me.

**Comment by lbnascimento** [comment]
@eschlot You got a few things wrong:

- You cannot use `SELECT $` with `group by` because `$` refers to the current document being iterated through *before* grouping. If you want to retrieve an array of all documents that were grouped, use `*`;
- The field `SHA` is the grouping expression, and due to a limitation in LiteDB, you can only access the grouping expression in your projection by using the special field `@key`;
- Given that the `SELECT` clause is the last one to be processed, you cannot use aliases in the `HAVING` clause (I believe the same is true even for relational databases)

So, I think your query would look something like this: `SELECT * AS items, @key, count(*) AS c FROM picturedata GROUP BY SHA HAVING count(*) > 1`.
