### ISSUE TITLE
[QUESTION] Why would I ever insert or update versus upsert all the time ?

### ISSUE THREAD

**Issue by stephenhauck** [mbdavid/LiteDB#1755]
Is there a reason that I would insert or update versus upsert by default all the time ?

**Comment by lbnascimento** [comment]
@stephenhauck Running Insert or Update should have better performance than Upsert (Upsert works by trying to update, and inserting if it fails). Also, Insert is "safer" because you don't run the risk of overwriting an existing document (by setting the wrong id) when you wanted to insert a new one.

Other than that, I don't see any reason.

**Comment by nightroman** [comment]
I think Update is a very different operation comparing to "Upsert update".
Update is supposed to change the specified fields.
Upsert replaces the whole document, if it exists.
Or am I missing something?

**Comment by lbnascimento** [comment]
@nightroman Both `Update` and `Upsert` replace the entire document. In fact, they call the same method in the engine (`LiteEngine.UpdateDocument(...)`).

LiteDB does not currently support updating only certain fields of a document. We are thinking of ways to implement it, but it seems to be a challenge, given the current architecture of LiteDB.

**Comment by stephenhauck** [comment]
Replacing works just fine .. spend time on other aspects that need attention would be my suggestion.
I am just used to a database that knows it has an "oid" and simply updates or inserts or like SQLite replace into.

Thanks
