### ISSUE TITLE
How can i get the autoid from a poco record

### ISSUE THREAD

**Issue by BobMcKay** [mbdavid/LiteDB#1757]
Hi,
I have a class:
public class x
{
public string a {get;set;}
public string b {get;set;}
}

insertion is:
x record = new x();
record.a="a";
record.b ="b";
ILiteCollection<x> collection = db.GetCollection<x>("records");
collection.Insert(record);

get records:
ILiteCollection<x> collection = db.GetCollection<x>("records");
List<x> records = collection.FindAll().ToList();
foreach (x record in records)
{
Debug(x.a); // fine
Debug(x.b); // fine

BsonValue id;
// how can i get the id for delete the record?

//collection.delete(id);
}

thx

**Comment by lbnascimento** [comment]
@BobMcKay The first (and recommended) way would be to add a `ObjectId Id { get; set; }` field to your class. If that is not possible, you could simply store the value returned by the `Insert` method (it returns the id of the inserted document). If that is not possible, your best option would probably be to use `DeleteMany` instead of `Delete`: `collection.DeleteMany(r => r.a == x.a && r.b == x.b)`.

**Comment by BobMcKay** [comment]
@lbnascimento Thank you for the fast response.
the ObjectId field is the solution. Next time i will read the docs more carefully. :)
