### ISSUE TITLE
Object Property List(of Object) - .contains not working

### ISSUE THREAD

**Issue by stigzler** [mbdavid/LiteDB#1758]
Consider the below:

```
public class mRom
	public property Name as String
end class

public class mGames
	<BsonRef("mRoms")>
	public property AllRoms as List(of mRom)
end class

ugame = db.Collections.mGames.Include(Function(x) x.AllRoms).FindById(ssGameId)
If Not ugame.AllRoms.Contains(rom) Then ugame.AllRoms.Add(rom)
```

This is to review AllRoms and add `rom` to the list if an instance of `rom` isn't already in the list. HOwever, I get duplicate entries. 

The `.Contains` function never detects the presence of `rom`, even if it is already in the collection. 

What am I doing wrong?

**Comment by lbnascimento** [comment]
A few comments: 

1. Your classes don't have id fields. It is strongly recommended for all classes to be inserted in a LiteDB collection to have id fields (I don't even know how you're using `FindById` without it).

2. You're using `BsonRef`, which is used to indicate that a subobject (or a list of subobjects) is to be stored in another collection. This creates a reference, which is resolved upon retrieval. However, you still have to manually insert the real objects in the referenced collection. In your example, you would have to insert `rom` to the collection of roms, add it to `ugame.AllRoms` and then update `ugame` in the games collection.

3. You may run into problems due to the `Contains` method using the default equality, which is reference equality. You could either override the `Equals` method in your class or change it to `Any`: `ugame.AllRoms.Any(Function(x) x.Name = rom.Name)`

**Comment by stigzler** [comment]
Thanks @lbnascimento 

On 1 + 2, the code I post was just an illustration, so that wasn't the issue. However, point 3 worked a treat! Thank you.
