### ISSUE TITLE
FIPS compliant AES encryption

### ISSUE THREAD

**Issue by jeremycook** [mbdavid/LiteDB#177]
May I suggest using the FIPS-compliant `System.Security.Cryptography.AesCryptoServiceProvider` class for encryption. Organizations that require FIPS compliance will get it out of the box, and I suspect everyone else won't be concerned about the implementation, so long as it does its job.

[This article summarizes the issue nicely](https://cketkar.wordpress.com/2013/05/13/fips-compliance-aes-and-net-crypto/):

> In the land of .NET, there are many ways to perform AES encryption, unfortunately, not all of them are FIPS compliant.
> 
> * AESCryptoServiceProvider in the System.Security.Cryptography module: This class uses Windows CryptoAPI (CAPI) which uses RSAENH.DLL which is FIPS-compliant. In the .NET world, this is the best option for using AES in any mode of operation (e.g. CBC, CFB, OFB).
> * RijndaelManaged in the System.Security.Cryptography module:  This module is not FIPS compliant.  However, this class can be used to perform AES encryption in CBC mode only if the block-size is set to 128 bits and key length is in {128, 192, 256} bits. Due to feedback size issues, this class cannot be used to perform encryption in CFB/OFB modes. In essence, do not use this class unless you want to support block-sizes other than 128 bits.
> * AESManaged in the System.Security.Cryptography module: This is just a wrapper for the RijndaelManaged class where the block-size is fixed to 128 bits.   Obviously, this is not FIPS compliant and is only good for the CBC mode encryption of AES.  As anticipated, it does not support the feedback size and therefore cannot be used for CFB or OFB modes of AES.  Do not use this class.
>
> If you turn on the registry flag
> HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy
> only the FIPS compliant .NET crypto classes will work. In general, none of the classes ending with “Managed” will work since none of them, at least so far, are FIPS compliant.

Benchmarks that may help you think about performance: http://odetocode.com/blogs/scott/archive/2014/02/24/symmetric-encryption-benchmarks-with-c.aspx

BTW: I'm impressed to see that this bit of infrastructure can easily be swapped out by providing a different FileDiskService :smiley:

**Comment by mbdavid** [comment]
Hi @jeremycook, thanks for your comments. Yes, in this version FileDiskService is a complete out-of-box persist data layer aceess. I will read more careful about this FIPS compliant.

**Comment by mbdavid** [comment]
Added reference to #20

**Comment by ItSkary** [comment]
@mbdavid : i see that ECB mode is use with AES : 
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Disk/Streams/AesStream.cs
![image](https://user-images.githubusercontent.com/6507710/101915618-237ead80-3bc6-11eb-90c2-eab2ba3ee1ac.png)

While is true that ECB is FIPS compliant, is highly recommended not to use that kind of encryption mode, because it could potentially leak information if an attacker can submit data in the cipher (basically if an attacker can save datas in the DB, a very common scenario).

From a security standpoint CBC mode is the first thing that came to my mind,  but i suppose that it's chain nature (not parallelizable, with dependency between blocks and may be error) could be difficult to handle in a DB.
But my question is, why any counter mode can't be used? (https://en.wikipedia.org/wiki/Galois/Counter_Mode)
I image that each data submitted is stored in a "memory page" or something similar that remain bounded with the data as long they live; so IMHO should be possible to tangle those two information to increase security.

I report here the why ECB is not safe :

https://crypto.stackexchange.com/questions/42891/chosen-plaintext-attack-on-aes-in-ecb-mode

**Comment by yariker** [comment]
It would be great to see some explanation as to why the ECB was chosen over the more advanced CBC.
