### ISSUE TITLE
[QUESTION] Beginner - Trying to find obtain a value from LiteDB

### ISSUE THREAD

**Issue by Gavenatore** [mbdavid/LiteDB#1831]
Hello
It is my first time using LiteDB and I am stuck. I am trying to read an int from my LiteDB.

`var iLatestID = MainDB_Coll.FindOne(Query.All("iID", 1));`
`if (iLatestID == null)`
`{`
`    MessageBox.Show("NULL");`
`    DatabaseTemplate.iID = 1;`
`}`
`else`
`{`
`    MessageBox.Show(int.Parse(iLatestID.ToString()).ToString()); //PROBLEM`
`    DatabaseTemplate.iID = int.Parse(iLatestID.ToString()) + 1;`
`}`

Seems like `int.Parse(iLatestID.ToString()).ToString()` returns a false string...
Why ?? :/ :/

Thank you for your time

**Comment by lbnascimento** [comment]
@Gavenatore I didn't understand exactly what your issue is, but I see a few things wrong with your code. You're assuming that `FindOne(expr)` returns an int, or an string that can be parsed to an int, which is not true. It returns an entire document, either mapped back to your original C# class if you're using a "typed" `LiteCollection`, or a `BsonDocument` if you're not using a "typed" `LiteCollection`.

I could help you further if you better explained your issue and if you explained what you're trying to achieve.

**Comment by Gavenatore** [comment]
Oh I am sorry. My bad...
To put it simply. I have successful created a LiteDatabase with 2 columns. 

iID and sName.
Then I added 3 records.

1st record: 0 George
2nd record: 1 Paul
3rd record: 2 Mary

I want to read from the last record, the iID.

**Comment by lbnascimento** [comment]
@Gavenatore If you're using a typed `LiteCollection<T>`, `FindOne(expr)` returns an object of type `T`. So, you access its fields just like you would on a regular C# object.

**Comment by Gavenatore** [comment]
Huh, it was much simpler than I thought.
Sorry for the novice question thread and thank you for your time.
