### ISSUE TITLE
Suggestion: Pass logging event message as Json

### ISSUE THREAD

**Issue by Abdul-Rahman-Ahmad** [mbdavid/LiteDB#188]
Hi,

It is possible to pass logging event message in Json format, So we can easily separate information ?

For example:
`{`
     `"Date": "0001-01-01T00:00:00.0000000Z",`
      `"Level": "COMMAND",`
      `"Collection": "colName",`
      `"Action": "Update",`
      `"Target": "Document",`
      `"Id": 1`
      `"Serial": 10023`
      `"Message": "any message if required"`
`}`

Thanks a lot.

**Comment by mbdavid** [comment]
Hi @Abdul-Rahman-Ahmad, I'm guessing that you want's an oberservable database to track changes. Log is used only to debug proposes and aren't the a good solution.

Track changes isn't simple when you think in a concurrent datafile. Each LiteDatabase instance can't checks if another LiteDatabase instance changed because there are no centralized service. I beleave that are easy to implement a repository pattern over LiteDatabase that track this for you (so you can control using static track changes )

**Comment by Abdul-Rahman-Ahmad** [comment]
Thanks @mbdavid , you are right.
