### ISSUE TITLE
Litedb - blazor

### ISSUE THREAD

**Issue by andreatosato** [mbdavid/LiteDB#1930]
Hi @mbdavid,
I saw Twitter that you declare that litedb work with blazor wasm.
Now version 5.1 Is in preview.
Can I try It?

**Comment by mbdavid** [comment]
Hi @andreatosato, my plans is release wasm version in 5.1 because 5.1 version back to 1 single file.... and it's better to store only 1 single file. I had some issues about multiple tabs.... 
Version 5.1 still in development and are on branch 5.1. Wasm are not in this repository yet because wasm will be a extensions for 5.1. I will submit to a new github repo and paste here so you can try

**Comment by andreatosato** [comment]
I present LiteDB to first datasaturday event: https://datasaturdays.com/events/datasaturday0001.html
I would like to talk about LiteDB for Blazor Was in addition to the classic presentations with Xamarin and local applications.
I saw that Azure is not supported, correct?
Are there any other scenarios where LiteDB makes a difference?

**Comment by mbdavid** [comment]
Hi Andrea, that so cool! I already registered to watch your presentation :)

LiteDB is more focused for embedded solutions when you don't want a central database server or you need a staging/local database. That's why there is no server version (yet, because I had future plans to offer LiteDB as web server service).

LiteDB 5.1 can works with a single abstract `Stream` class. Internal database pages access only by 8192 bytes per time (read/write). So, the ideia in Blazor are implement a "in-browser" `Stream` access, using localStorage (sync) or IndexedDB (async). For first test I implement only a synced version using localStorage.

But it was a first tests, need be implement more "multiple-tabs" data access to avoid database corruption (2 browser tabs changing different pages). So that's why I haven't published yet.

If you need any help with our presentation content, let me know...

**Comment by andreatosato** [comment]
Yep, i Need content for presentation 🤗.
I use litedb manu times but i want to explain all scenarios.
Can I try early preview with localstorage? Can I advertise user that in next version will be another option for blazor?

**Comment by mbdavid** [comment]
LiteDB for Blazor will be another repository with a LiteDB fork version (5.1) using  of LiteDB

My first test works only with synced LocalStorage methods call. For first test are ok, but for better results in browser enviorment async must be used (my plans are use async `IndexedDB` for local storage data pages). I already know how to do this and I will submit this project next few days (aka my vacation 😄)

Main idea here:

https://github.com/mbdavid/LiteDB.Blazor

**Comment by andreatosato** [comment]
Oh great!
I create repo for conference.
I think that create 50 of live coding and 10 minutes with presentation.
Talk will be in italian 🇮🇹.

I link my repo here, now close question.
Thanks a lot @mbdavid

**Comment by andreatosato** [comment]
@mbdavid I run your sample. 
In the example, the database is saved in memory.
You mention the possibility of using it with IndexedDB and localDB but I don't see any references. 
Could you give me some indication?

**Comment by mbdavid** [comment]
My first example was just project init. This new version need use ReasAsync because Blazor works only in async. Now I'm refactoring all source to works with async methods.

**Comment by mbdavid** [comment]
Hi @andreatosato, there is a first version of LiteEngine avaiable in blazor repository. This first working version use only async calls to all methods. You can "see" your Stream in LocalStorage keys.

![image](https://user-images.githubusercontent.com/1137197/107557935-f72ce080-6bb8-11eb-9fcc-5d35ee0bd6b4.png)

**Comment by andreatosato** [comment]
Oh great work.
Next week I try It and write some demos

**Comment by andreatosato** [comment]
Hi @mbdavid, do you have some presentation content for LiteDB?
I'm working with some [samples](https://github.com/andreatosato/LiteDbSamples)
I think that code sample and doc are enough to introduce the LiteDB.
If you have specific content or presentations, I would be happy to use them.

Thanks a lot @mbdavid
