### ISSUE TITLE
Test DbRefIndexe_Test failed

### ISSUE THREAD

**Issue by luis4ndre** [mbdavid/LiteDB#202]
This Test fail if is executed alone, but pass if is executed all tests.

Test method LiteDB.Tests.DbRefIndexTest.DbRefIndexe_Test threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
LiteDB\LiteDB\Serializer\Mapper\Reflection.cs:line 95

tnks.

**Comment by mbdavid** [comment]
Are you using master branch? We are changing reflection class to support PCL plataform. Please, test `v2mine` branch.

**Comment by luis4ndre** [comment]
Yes, I was on master, on v2mine it works.

Tks

**Comment by negue** [comment]
Good catch, it fails because the new `LiteDbPlatform` wasn't initialized like everyother test within a `TestBase`, gonna fix that in a second.

The real problem is that `BsonMapper` is called before `new LiteDatabase`, which can't call the Platform's Initialize and then fails that `LiteDB.Core.LiteDbPlatform.Platform` is null.

**Comment by negue** [comment]
fixed in master
