### ISSUE TITLE
[BUG] AutoId counter is not persistent

### ISSUE THREAD

**Issue by fraenke75** [mbdavid/LiteDB#2042]
1st of all: Many thanks for sharing this great database library!

I'm using the newest LiteDB 5.0.11.0 with .Net 5.0 Core on a Windows 10 20H2.

In my application I dump my log entries into a shared LiteBD database which works great. The log entries have a unique ID which is set as AutoID from type Int64.
To limit the database size I need to delete old entries (with the lowest Id's) from the database from time to time. This is done in a different process and independent from the Logging, so I need to work with Shared databases and I cannot resue the 

I found that there is a unit test _AutoId_No_Duplicate_After_Delete()_ which does exactly what I would expect, but it is failing when Database in closed in between. Please find my modified code here as explanation:

```
var memStream = new MemoryStream();
using (var db = new LiteDatabase(memStream))
{
    var col = db.GetCollection<EntityLong>("col2");

    var one = new EntityLong {Name = "One"};
    var two = new EntityLong {Name = "Two"};

    // insert
    col.Insert(one);
    col.Insert(two);

    one.Id.Should().Be(1);
    two.Id.Should().Be(2);

    // now delete 2nd row
    col.Delete(two.Id);
}

using (var db = new LiteDatabase(memStream))
{
    var col = db.GetCollection<EntityLong>("col2");

    var three = new EntityLong { Name = "Three" };
    var four = new EntityLong { Name = "Four" };

    // and insert new documents
    col.Insert(new EntityLong[] { three, four });

    three.Id.Should().Be(3);           //Exception that ID is 2 - I would expect 3 like in the original test
    four.Id.Should().Be(4);
}
```

**Comment by lbnascimento** [comment]
@fraenke75 This is an unavoidable consequence of how LiteDB implements auto-id. The last used id is kept in memory and incremented with each insertion. It is never decremented, which is why it works as you would expect before closing the datafile. When the datafile is closed and reopened, the auto-id is recreated in memory from the largest id stored in the collection.

I believe this behavior is currently undocumented. I'll try to improve our documentation.

This might be changed in future versions of LiteDB, but given that this is not actually a bug, I'll close this issue for now.
