### ISSUE TITLE
How to map constructor using fluent mapping

### ISSUE THREAD

**Issue by nunonux** [mbdavid/LiteDB#2060]
Hi there,

First I want to say that I've searched for a solution, but didn't found one. So, I'm having some difficulty to map a constructor using the fluent mapping. For example, I have a class, "User", it have a constructor with 2 parameters, something like `User(string username, ProfileRole profileRole)`. How can I map it using the fluent mapping?

**Comment by lbnascimento** [comment]
@nunonux You could do something like this:

```C#
BsonMapper.Global.Entity<Sample>().Ctor(x => new User(x["Username"], BsonMapper.Global.Deserialize<ProfileRole>(x["ProfileRole"])));
```

The constructor mapping is only meant for simple cases (e.g. using the construtor that takes an `int` and a `string` instead of the parameterless constructor). If you need to pass complex types and enums to the constructor, it's probably best to create custom serializer and deserializer with `BsonMapper.Global.RegisterType<T>(...)`.

**Comment by nunonux** [comment]
Thanks for the reply. 
This worked for me.
