### ISSUE TITLE
Implement IQueryable interface

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#217]
It would be nice if this implemented IQueryable so that you can fully use LINQ instead of just the Find method you implemented.

**Comment by mbdavid** [comment]
Hi @emrys90, IQueryable was my first try. But it´s quite complex to do and db engine must implement all function to be worth.

Also, because LiteDB is local database, amost other functions than Where/Skip/Take is implemented using LINQ to Object is fine.

**Comment by jeremycook** [comment]
Seconding @mbdavid comment.

@emrys90 I use EF everyday and perceive the benefit of supporting IQueryable in the way EF, L2S and other ORMs have. Nonetheless my preference would be to avoid doing so because fully supporting IQueryable is a massive undertaking that is difficult to produce anything other than a misleading API. I like how relatively small and simple LiteDB is, and believe IQueryable support (as I imagine you are thinking of it) would undermine that. I also like that LiteDB's current API unambiguously reflects what LiteDB can actually do.

And here's a more theoretical rationale http://blog.ploeh.dk/2012/03/26/IQueryableTisTightCoupling/

**Comment by emrys90** [comment]
The biggest reason I would want support for this is for things like multi-database support. On the backend I could do things a little differently, but then return an IQueryable interface that uses the same models for the different ORM and have everything that use this require no changes. So different databases would be pretty much plug and play. I suppose I could get around this in other ways though.

**Comment by mbdavid** [comment]
@emrys90, in my all-day work, I use NPoco micro ORM that contains a "IQueryable Like" interfaces that I like it! It´s very simple and efficient way to write 95% of data maniputation in a project. I have plans to write a project that implement an repository pattern using this "IQueryable like" class (outside LiteDB project).
