### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by FoxTes** [mbdavid/LiteDB#2174]
For the sake of interest, I decided to test the creation of a connection to the database. Tell me, why does it take so much memory? Creating a connection should consume as few resources as possible (for example, EF Core). In this case, a very strong load on the GC is obtained.

Code:
```
    [Benchmark]
    public void LiteDatabase()
    {
        using var db = new LiteDatabase(@"MyData1.db");
    }
    
    [Benchmark]
    public void LiteRepository()
    {
        using var db = new LiteRepository(@"MyData1.db");
    }
```

Result:

```
|         Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|--------------- |---------:|--------:|--------:|--------:|--------:|--------:|----------:|
|   LiteDatabase | 337.0 us | 5.64 us | 5.00 us | 30.7617 | 30.7617 | 30.7617 |    120 KB |
| LiteRepository | 334.0 us | 3.35 us | 2.79 us | 30.7617 | 30.7617 | 30.7617 |    120 KB |
```

**Comment by mbdavid** [comment]
Hi @FoxTes,

When you create a new `LiteDatabase` instance (or `LiteRepository`, because `LiteRepository` is only a pattern over `LiteDatabase`) initialize an initial memory allocation with 80K for page cache. This memory allocation grows according new page reads (take a look on `MemoryCache.cs`).

I agree that connections should consume few resource (like in EF Core), but `LiteDabase` is the database engine (not only the connection).

Thanks for your review and tests, I'm re-writing database engine to be more memory efficient in next version and possible use EF Core as data provider.
