### ISSUE TITLE
Query against child properties

### ISSUE THREAD

**Issue by WaywardMage** [mbdavid/LiteDB#221]
I have a class Post which is stored in the collection "post".  Each Post has a nullable "Tags" property which is List<Tag>.  Tag has a property "Name".  How can I query my posts where a given tag has a name of "mytag" ?

I tried 

posts.Find(p => p.Tags.Any(t => t.Name == "mytag"))

and I also tried

posts.Find(Query.In("Tags.Tag.Name", "mytag")) 

both return System.InvalidOperationException. The former with "variable 'p' of type 'Post' referenced from scope '', but it is not defined" and the latter with "sequence contains no elements"

I tried a few other options:

.Find(p => p.Tags != null && p.Tags.Any() && p.Tags.Any(t => t.Name == "mytag")) --  "Index was out of range. Must be non-negative and less than the size of the collection"

.Find(p => p.Tags != null && p.Tags.Count() > 0 && p.Tags.Any(t => t.Name == "mytag")) -- " Invalid type owner for DynamicMethod"

Am I missing something obvious or is this just not supported?

**Comment by mbdavid** [comment]
Hi @WaywardMage, this are a missing feature in LiteDB. You need is a "Multikey index" (see https://docs.mongodb.com/v3.0/core/index-multikey/).

Document store databases has many kinds of indexes: (see https://docs.mongodb.com/v3.0/core/index-types/). LiteDB, in current version, support only most used one: "Single Field Index".

And with my current engine it´s not possible implement. Is on my plans, no next major version, re-write all engine system just because this: multikey indexes and compound indexes).

So, for this operation you will need use a non-indexed query, like:

`.FindAll().Where(p => p.Tags != null && p.Tags.Any(t => t.Name == "mytag"));`

**Comment by WaywardMage** [comment]
That worked. Thanks for the tip!

**Comment by vip32** [comment]
@WaywardMage 
are you (or another contributor) working on a multi-key index implementation? this project looks very cool and usable, however this querying into child object lists is a must for must use cases (get customers with specified tags, get orders with specified products). cheers!

**Comment by mbdavid** [comment]
Hi @vip32, I'm working on it on `dev-mk` branch. I believe that will be present in v3 version.

**Comment by Still34** [comment]
@mbdavid Is this addressed? Because it still throws for me with a similar situation here in the latest version.

**Comment by mbdavid** [comment]
Hi @Still34, if you are using v3/v4 it's possible works with MultiKey Index. You can see here: https://github.com/mbdavid/LiteDB/issues/474#issuecomment-279091158 or here https://github.com/mbdavid/LiteDB/issues/915
