### ISSUE TITLE
Is it will support LINQPad?

### ISSUE THREAD

**Issue by wellxion** [mbdavid/LiteDB#23]
like it's data context driver

**Comment by mbdavid** [comment]
Hi @wellxion, I never used LINQPad, but reading about It needs a special driver context to works.

At this point, LiteDB supports only simple find Linq expressions and no IQueryable implementations. In future, I want implement more complex query results and them LINQPad can be a good tool for LiteDB.

**Comment by wellxion** [comment]
LINQPad is a powerful and convenient tool, I think this might be a nice future to support it.
By the way, LiteDB is the best what I needed. Hope It can be better.  :D

**Comment by 178220709** [comment]
Aha,this is a really good idea.
Except the command console ,seems there is no gui tools to manager LiteDB (just like pl/sql MongoVUE) 
LINQPad may be a good choice .

**Comment by jamesmanning** [comment]
:+1: for a LINQPad driver - would be awesome to have!

Not sure if it helps any, but I noticed there's already a driver for a very similar (AFAICT) project FileDB @ http://www.eztools-software.com/tools/FileDb/linqpad.asp

That driver appears be available to use under Apache 2.0 from https://code.google.com/p/filedb-database/source/browse/trunk/Src/LinqPad+Driver?r=21#LinqPad%20Driver%2FSrc so maybe it's 

I realize that's not the same FileDB project @mbdavid had done @ http://filedb.codeplex.com/ so apologies for any confusion caused by this.

In case it helps any, I exported the filedb-database project from google code to github so you can clone it a little easier:

https://github.com/jamesmanning/filedb-database/tree/master/Src/LinqPad%20Driver/Src

**Comment by jamesmanning** [comment]
Since LiteDB tries to follow MongoDB (AFAICT), a better starting point might be a MongoDB driver for LINQPad

https://mongolp.codeplex.com/

Underneath it uses https://github.com/craiggwilson/fluent-mongo

**Comment by cseder** [comment]
+1 for LinqPad support!
I've used LinqPad a lot and being able to use LiteDB + LinqPad would be awesome! :)

**Comment by Jack85** [comment]
+1 for LinqPad
its awasome

**Comment by adospace** [comment]
I've developped a LinqPad driver for LiteDB 3.0:
https://github.com/adospace/litedbpad

Pls check it out

BTW LiteDB is awesome!

**Comment by jamesmanning** [comment]
@adospace that's great, thank you!

**Comment by ferronicardoso** [comment]
Excellent job!

**Comment by mbdavid** [comment]
Nice one! Thanks! I'm adding you project as reference in README.

**Comment by GitOffice** [comment]
@adospace  any tutorial or sample using litedbpad？
