### ISSUE TITLE
Endianness for BSON serialization

### ISSUE THREAD

**Issue by izackp** [mbdavid/LiteDB#295]
I noticed that there isn't any endian conversion on reading or writing binary data. This maybe a problem if anyone were to transfer their database from a computer with one endianness to a computer with another endianness. 

If they used anything besides char or single byte values then they would be reversed upon reading the data. I would recommend storing all data in one format (little endian or big endian) so when the data is read you can convert it properly to whatever endianness the computer supports.

**Comment by izackp** [comment]
Whoops, I'm using an outdated version of litedb. Looks like you're using bitconverter which automatically handles this.

**Comment by mbdavid** [comment]
Hi @izackp, yes and no. Current version uses both implementations: BitConverter and `unsafe` mode. This is because I did some performance tests and unsafe are faster than BitConverter (a tiny better)... In my dev branch I'm re-writing some conecepts about LiteDB and I try to modulate and be more simple as possible (in this case, use only BitConverter).
