### ISSUE TITLE
Can't read interface collections, e.g. IList, ICollection

### ISSUE THREAD

**Issue by cocowalla** [mbdavid/LiteDB#31]
I have a model with an interface collection property, `ICollection`, and seem to be able to store my models OK (at least, I don't get any errors, and the file size looks about right).

But when I try to read any of these models back from the LiteDB collection, the collection property contains no elements. Note that it works OK if I use a concrete type, like `List`.

**Comment by mbdavid** [comment]
Hi @cocowalla, I was looking how mongodb resolve this problem: basicly is using concrete classes when deserialize. I will try do the same.

**Comment by francoislg** [comment]
I tried something this afternoon about this.

How I see it, is that you need to store the original type of the array in a BsonArray and save it in the database, so that when you load it back it creates the type stored.

I couldn't manage to do it, but it looks like going this way would probably solve https://github.com/mbdavid/LiteDB/issues/30 also
