### ISSUE TITLE
Capped Collection in LiteDB

### ISSUE THREAD

**Issue by Adstyle** [mbdavid/LiteDB#314]
Does liteDb support capped collection just like in Mongo? If there is no such thing, can you suggest the method to overwrite the document inside the collection once it reached the collection maximum size.

**Comment by mbdavid** [comment]
Hi @Adstyle, there is not such a thing in LiteDB. I readed about this collection type, ideal for high insert throughput. To implement this it's not easy because, by default, this collections has no `_id` index and are based on insert order.

If you have plans to works with a circular queue, you must implement an external structure do manage this.

**Comment by Adstyle** [comment]
@mbdavid thanks for the reply, yeah, if so i need to do a scheduler to do housekeeping for my db. thanks again david.
