### ISSUE TITLE
LiteDB v3 is wanted!!!

### ISSUE THREAD

**Issue by johnkea** [mbdavid/LiteDB#323]
Dear @mbdavid , sorry for flooding your issues but seriously when approximately you are planning to share v3 with us?

**Comment by mbdavid** [comment]
Hi @johnkea, my initial plan is Dec 1 as I mark in milestone due date. I belieave is a reasonable date to finish all feature I want and make/update unit tests.

**Comment by dampergud1** [comment]
will i then be able to use it in my .NETPortable 4.5?

**Comment by mbdavid** [comment]
Hi @dampergud1, in v3 LiteDB will be distribuided in 2 version:
LiteDB - Build for .NET 3.5
LiteDB.Core - Build for NetStandard 1.3 - (net46, netcore, xamarin, mono, uwp10)

So, portable .NET 4.5 will not be supported. Or you can use NET 3.5 full framework or PCL .NET 4.6

**Comment by lepigocher** [comment]
Hi Mauricio, Could you please respond also on gitter!? Yesterday I asked why you don't plan to use netstandard 1.4? It will be great to have a clear and simple explanation on such choice. Also I do not understand why LiteDB.Core will use netstandard 1.3 and LiteDB will use another Framework? It's very confusing. You probably have a good reason but it would really help to have a short page in the Wiki concerning this specific subject. This is a new project and moving, that's fine but if you want to get help from others you have to provide a few explanations. I know that's time consuming but again without explanation I don't know if I can help nor if I have to continue to invest time in learning your project. Don't misunderstood, it's NOT a complaint but we need informations to decide if we can help.

**Comment by mbdavid** [comment]
@lepigocher my choice to 1.3 it's only because 1.3 has all features I need (at least until now) to get LiteDB works to portable. After @szurgot research, in 1.3 also included Aes crypto classes.
I changed from PCL to NetStandard just because it's easy to get only 1 dll to portable that works in all platforms. That much better than has a lot of projects each one for a single platform. 
The cost benefit is much better.
I'm kepping .NET 3.5 too because many dev uses in Unity framework (which needs 3.5) and for desktop/web platforms that uses .NET 3.5, 4, 4.5.

But I'm open to new ideias! Please, continue to contributing.

**Comment by lepigocher** [comment]
@mbdavid : Hi Mauricio, thanks for the feedback. Please have a look at a more detailled response at gitter: https://gitter.im/mbdavid/LiteDB?at=58077aed48292577613a6c5c

**Comment by mbdavid** [comment]
Hi guys, it's done! v3-beta was released :)

**Comment by lepigocher** [comment]
That's GREAT!!! :-) Thank you Mauricio!
