### ISSUE TITLE
Is 4096 a good choice for page size?

### ISSUE THREAD

**Issue by nerai** [mbdavid/LiteDB#327]
Currently, the page size is fixed at 4096 bytes, which is the Windows size for disk access - a good fit.

However, considering that traditional hard disks are far faster at sequential than random access, it might be faster if the page size were larger.

Obviously, this would lead to more wasted time when reading only a single element from a page. However, this waste is probably very small, because the disk drive does not really care if you read 1 or 2 (or 5) pages - it's only a microsecond or so more, since the head is already at the right place of the disk.

At the same time, the larger page would contain a lot more co-located information, which is greatly advantageous for e.g. full scans. In short, we get a good chance for a significant performance improvement for almost zero cost.

This makes it look like an increase page size  (e.g. 8kb or 16kb or even more) would be beneficial.

On the other hand, I see these problems with an increased page size:
- When increasing volume too much, disk access does become slower, so we should not increase the page size to something ridiculous like 10 MB.
- Fragmentation within a page may be higher (not sure, did not check if this can be the case)
- Parsing the contents of a single page happens linearly, so parsing becomes slower (should not be a bottleneck, though, as disk access is magnitudes slower)
- The operating system may have worse caching behavior due to more, unnecessary pages read from disk. For instance, with 16kb pages, the OS can probably only cache 25% as many pages, which is bad in case of repeated reads of single elements in many different pages

**Comment by mbdavid** [comment]
Hi @nerai, when I decide to 4096 I search about all databases use. Many databases you can define page size, which is really nice do advanced users (really advanced - because it's hard to know if your choice will be best). Not only page size, but PCT Free and PCT Used is fine tune for databases. LiteDB works with 50% of PCT Free/Used.

LiteDB works with whole page operation for read and for write. So, change a single document, saves all affected pages (could be only 1 DataPage and N PageIndexes - if index keys changed). 

A long time ago I made some performance tests using 4k, 8k and 16k with no expressive diference.

The next version works with a single instance in memory and this will be really nice to performance. Mosted pages will be in memory (cache) and write in disk small pages could be faster than write bigger pages.

Do you have idea how to do good test performance to compare?

**Comment by nerai** [comment]
@mbdavid  It's definitely required to test with both HDD and SSD. I believe the page size change will only be useful for HDDs, while it is (probably) not useful or even hurtful for SSDs. So all tests should be performed with a traditional disk as well as an SSD.

As for the tests themselves, I'd go with the usual: read/write x sequential/random (4 combinations). So together, we get 2x2x2x3 = 24 combinations to look at:

- HDD / SSD
- read / write
- sequential / random
- 4k / 8k / 16k page size

Is this what you had in mind?

**Comment by nerai** [comment]
@mbdavid To make sure, there is something else I need to mention: The primary reason for increasing the page size is increasing data locality. Currently, data are often highly fragmented because pages of data that are related are not co-located in any way (when creating a new page, related pages are not considered). If we somehow were able to fix this (by keeping related pages close together on disk), then there would be no need to change the page size at all. I do not know if this is possible.

**Comment by mbdavid** [comment]
Documents are organized in data pages by collections. A single page contains only documents from same collection. Index pages are same idea: a single page contains only keys from same index/collection. This is used to keep, as much as possible, information together in same page.

It's not possible predict when next related page are required. It's possible only use reserve N pages when create collection. Another approach is use multiple files, one per collection and one per index.

About combinations: they are fine, it will test all options. To insert documents in sequencial way, is better upload large files (because uses Extended Pages). To random disk storage, insert in many collections, one document/collection per time.

**Comment by nerai** [comment]
@mbdavid Alright. Should we wait for the next version before testing? If you think it will be stable anytime soon, then no point in testing right now.

Also: Apart from the page size constant, what else do I have to change? Max number of documents per page probably, too?

**Comment by mbdavid** [comment]
Yes, next version will be best to test this. I working now in lock read/write operations and soon will be possible to test this.

If we made this tests and discover differences between page sizes can be add as parameter. Today, all constants are calculated by page size. To made tests it´s easy to compile LiteDB using compiler constants setting BasePage.PAGE_SIZE.

Current, a single page support up to 65536 (ushort.MaxValue) documents. But it´s never reached because there is no space to so much documents. Not even 32K or 64K page will use this (minimum document size, in v3, is 8 bytes when document uses Extended pages - In v2 this size is 100 bytes minimum).

**Comment by mbdavid** [comment]
Hi @nerai, v3-beta was released. Now we can test anothers page sizes before final release.

**Comment by nerai** [comment]
Hey @mbdavid, thanks for the heads-up, I'll try it out once I find the time.

**Comment by nerai** [comment]
To keep you updated, it will probably take a while before I can work on this. In the meantime, anyone feel free to go ahead as you wish.

**Comment by mbdavid** [comment]
To keep more update: next version will use PAGE_SIZE to control Lock file control. There is a new blank page (PageID 1) just to control this.

About lock
http://www.frenk.com/2010/03/leaky-abstraction-strikes-again-filestream-lock-gotchas/

I made a simple performance test to compare with SQLite with nice results. Maybe can be a start point to test more page sizes
https://github.com/mbdavid/LiteDB-Perf

**Comment by mbdavid** [comment]
Just closing this issue but if you have any news about that, just re-open
