### ISSUE TITLE
Collection names not encrypted

### ISSUE THREAD

**Issue by abreseeOpsec** [mbdavid/LiteDB#361]
Hi,

I'm testing out LiteDB. One feature that that I'm interested in is encryption. I've created a test database using the connection string "filename=testDB.db;password=test", created a collection named "CollectionNameTest", added an object to it, and opened the file in a hex editor. While most of the file appears to be gibberish, I can read the name of the collection I created in plaintext. 

![collection name shown](https://cloud.githubusercontent.com/assets/18487417/20900910/1c748228-bafe-11e6-8f26-a27dbf0c7a9d.png)

Is this a limitation of LiteDB? are all collection names stored unencrypted even when using encryption? If so, what else isn't encrypted? 
Or am i simply doing something wrong?

For reference, this is the block of code I'm using to create the collection. 

``` c#
const string CollectionName = "CollectionNameTest";
const string storedValueKey = "storedValue";
const string connectionString = "filename=testDB.db;password=test";

using (var db = new LiteDatabase(connectionString))
{
    var saveValue = TextBoxText;
    var coll = db.GetCollection<Entity>(CollectionName);
    var entity = coll.Find(x => x.Key == storedValueKey).FirstOrDefault();
    if (entity == null)
    {
        entity = new Entity { Key = storedValueKey, Value = saveValue};
        coll.Insert(entity);
    }
    else
    {
        entity.Value = saveValue;
        coll.Update(entity);
    }
}
```

I am using 3.0.0-beta2 from Nuget.org

**Comment by mbdavid** [comment]
Hi @abreseeOpsec, this "feature" is know when I wrote encryption. Header page (PageID = 0 / first 4096 bytes) are not encrypted because SHA1 password are stored there. And I need this hashed password to compare with user passed password.

You can see here:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Services/PageService.cs#L39

and here:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Services/TransactionService.cs#L71

Header page contains all collections names and some link pointer to data file. All user data (like documents, indexed keys, files) are encrypted.
