### ISSUE TITLE
Question - rysnc on a live database?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#371]
Just a quick question - I was wondering how reliable a backup of a live database (i.e. one that it being written to) would be if taken with rysnc or similiar?

From what I can tell, it may possibly work quite well. I see that LiteDB writes changes to journal files first and then merges them into the DB. If the DB is left in an inconsistent state, LiteDB can recover using the journal files. This should mean that copying a live DB may work quite provided that the copy of the DB and journal file are not both in an inconsistent state.

Any thoughts on this?

**Comment by mkosieradzki** [comment]
I have following thoughts - please correct me if I am wrong!

1. You can try to copy entire db file (ignoring journal!). If you get exclusive lock on database file - database SHOULD be in consistent state (unless it is a reboot after power-off event - in that case this approach will fail!)
2. Use volume shadow copy service (VSS) on Windows and copy both files from single VSS snapshot - both files should be in mutually consistent state as you have suggested. For example ntbackup utilizes VSS.
3. Acquire exclusive lock on both files (journal and db) then copy both files. At this point @mbdavid  can possibly suggest which order of acquiring locks is correct to prevent deadlocks. I would guess the following:
a) open database file
b) check if journal exists - if it does exist it means it's remainder from power failure. Otherwise (I guess!!!) you wouldn't be able to successfully complete 'a'. Copy and close journal.
c) copy database file
d) close database file

Point 2 is perfectly safe and it ignores locking. You can treat VSS as an instant "power-off" snapshot. I have no experience how to do VSS-like copy on linux.

**Comment by kuiperzone** [comment]
Thanks for the response!

Rsync is LINUX/UNIX utility -- I'm actually thinking about running this on LINIX under EXT4 and .NET Core (or Mono). I don't imagine rsync is going to respect file locks (they are optional under LINUX).

The LVM links interesting. Thanks for that.

**Comment by mbdavid** [comment]
Hi guys, as @mkosieradzki says, to make a copy you can:

1) Open datafile in exclusive mode
2) Checks if exists journal file - if exists, close it and open again using LiteDB to recovery and open again in exclusive mode
3) Copy datafile only

**Comment by mdissel** [comment]
Maybe add a method to the LiteDbEngine to make a backup of the database to another directory?

**Comment by kuiperzone** [comment]
I thinking ahead myself about being able to backup a live DB because I planning (hoping) to run this continuously on a Linux box. However, I don't really expect the developers to focus on this kind of application. I think having LiteDB perform backup on a live DB (i.e. one that is changing) is asking a little much of a project that it is designed to be an embedded database for desktop and phone apps. Added features and complexity bring added maintenance and bugs.

Nevertheless, one really neat solution for a client app may be to call "BeginTrans()" prior to backing up the DB. If I understand it correcly, live changes would then be written to the journal files while rsync could be used to copy the main file. Once complete, Commit() could be called to roll the changes into the main DB.

**Comment by mdissel** [comment]
> I think having LiteDB perform backup on a live DB (i.e. one that is changing) is asking a little much of a project that it is designed to be an embedded database for desktop and phone apps.

One of the reasons to use an embbed database is that there's zero maintenance and/or additional installation is necessary. The application itself can implement a backup strategy using the Backup method
The same method can be called from the shell.
