### ISSUE TITLE
Journal file corruption

### ISSUE THREAD

**Issue by jbakholt** [mbdavid/LiteDB#387]
What are the chances of the journal file being left in a corrupted state after after a failed write (after loss of power or something else totally unexpected).

The reason for asking is that LiteDb doesn't seem to handle a corrupted journal file very well at all. In fact it seems to go into some sort of infinite loop.

To reproduce the odd behavior just make a console app with a loop that stores a big load of events (10000's). Execute the app and just stop it at some point and hopefully the journal file is larger than 0 KB. If that's the case open the file in notepad and add "123" in the beginning of the file and save. Then restart your console app. It should now go into a endless loop. Be prepared to hard reset your computer.

**Comment by mkosieradzki** [comment]
If you use journalled file system it is very unlikely (serious hardware failure), you should usually end up with issues on page-level (like entire page is uncommited).

Last time I have seen actual file corruption was ext2 and fat32.

However adding some CRC32 validation doesn't seem like a bad idea.

**Comment by mbdavid** [comment]
LiteDB doesn't check this manual changes in file (journal or datafile).

It´s safe override your datafile using a "corrupted" journal file because journal file IS original datafile. If application stops during journal write mean datafile are "clean".

In some tests that I made, NTFS always write page-level data. Never writes a "half-page".

And yes, CRC32 are missing be "more sure" about this. It's on plans (and reserved space in header too)

**Comment by jbakholt** [comment]
CRC32 would definitely add an extra layer to the verification of the integrity of the files. If the CRC32 check fails or for some reason can't be executed then LiteDb should throw an exception and abandon execution IMO. It should never go in to a loop like the one that actually required me to hard reset my entire computer because it became unresponsive. That was really a weird :o)
