### ISSUE TITLE
If delete a collection, database size is not reduced. Why?

### ISSUE THREAD

**Issue by ambyte** [mbdavid/LiteDB#40]

**Comment by mbdavid** [comment]
Hi @ambyte, LiteDB do not reduce disk space because It´s needs a shrink process to do that. When you delete a collection the space allocated are not in sequence on end of file. All data are in logic pages (with 4096 bytes each) inside data file.

But, all deleted pages will be reused in next add documents and datafile will grow only when there is not more empty pages in datafile.

In future version LiteDB will have a shirink operation that can be compact datafile. This operation is not automatic. If you see all databases (nosql or relation) do the same way.
