### ISSUE TITLE
v3.0.0 - beta3 - Question regarding the Fluent Mapper with Index

### ISSUE THREAD

**Issue by Splamy** [mbdavid/LiteDB#408]
I'm quite new to LiteDB and this seems kinda strange to me.

Why does the Fluent Mapper throw a `ArgumentNullException` here:
```
BsonMapper.Global.Entity<TesBase>()
	.Id(x => x.Id)
	.Index(x => x.Value)
	.Index(x => x.Embed.Import) // <= Problematic line
	;
```

while this works perfectly:
```
var audioLogEntries = db.GetCollection<TesBase>("base");
audioLogEntries.EnsureIndex(x => x.Embed.Import);
```

Used classes:
```
class TesBase
{
	public int Id { get; set; }
	public string Value { get; set; }

	public TesEmbed Embed { get; set; } = new TesEmbed();
}

class TesEmbed
{
	public string Import { get; set; }
}
```

**Comment by mbdavid** [comment]
It's happend because you are modeling `TesBase` and not `TesEmbeded`. When you write `x.Embeded.Import` mapper try find `Import` property in `TesBase` and not found.

In this case, you must use `EnsureIndex` or do nothing - indexes are auto-created when you run any query. Explicit indexes are useful only when you want create unique index (default index are not unique) or a virtual field, like `.Index("myindex", (item) => item.FuncOverDocumnet());`

**Comment by Splamy** [comment]
Ah, thank you!
