### ISSUE TITLE
Question - Possibility of <Expression<Func<t_model, Boolean>> on orderby method

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#443]
Good aftertoon @mbdavid,

LiteDB really works like a charm. On that other case, of mappings, I found a very nice solution for my architecture but, the question here today is different.

As I'm building a DDD application, I use ninject for dependence injection and auto-mapper do handle some mappings.

The question is: since orderby on liteDB is a delegate Func<,> (one of the overrides), isn't possible to implement on order by an expression like Expression<Func>> ?

this way I can use auto-mapper to mapping these expressions. With delegates the types are unknown for mapping.

To make things clear, see this link:

[https://github.com/AutoMapper/AutoMapper/issues/1927](https://github.com/AutoMapper/AutoMapper/issues/1927)

Thank u again for such great tool like liteDB.

[],
regards

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, where are you using orderby? LiteDB doesnt implement any algorithm to order by results. The only option LiteDB has is support ASC/DESC option when you quering using some index.

Since LiteDB is local database, there is no need to implement custom orderby. You can use `OrderBy` expression from LINQ extensions.

**Comment by rmszc81** [comment]
Hi @mbdavid,

You're right, now I see that's from IEnumerable interface.

It's a local app, just a research of my own, not a professional product
really.

I did what I need with IQueryable.

Thanks a lot. You can close the thread.

[],
Regards,

@rmszc81
