### ISSUE TITLE
Question : How can i map derived interfaces?

### ISSUE THREAD

**Issue by aytacasan** [mbdavid/LiteDB#444]
I have an IData interface which have Id property. Also i have an ICustomer interface which is derived from IData interface. I want to write that `BsonMapper.Global.Entity<ICustomer>().Id(e => e.Id).Index(e => e.Name, true)` but receive null reference exception because mapper can not find Id property in ICustomer interface. I want to map with interface because later i'll access customers collection like that `GetCollection<ICustomer>("Customers").` If i use Customer instead ICustomer when do mapping, indexes not creating correctly (Name index creating unique=false). This behavior not make sense for me. How can i solve this problem?

**Comment by mbdavid** [comment]
Hi @aytacasan, you can't run Entity<Interface>, only concrete classes. I will mark this as an issue, because I planning change this to be more flexible, like this:

`BsonMapper.Global.Entity<ICustomer>(t => typeof(ICustomer).IsAssignableFrom(t)).Id(...)`

**Comment by aytacasan** [comment]
Hi @mbdavid, you are the owner of LiteDB and i'm newbie. I hope in time i'll be more familiar source code of the library so i'll be more constructive about it. But at the first glance your plan looks like correct & best solution. It'll be really flexible...

**Comment by cyberjaws** [comment]
Would this also resolve this case (or provide a work around?):

public interface IDbItem {
   object Id { get; set; }
}

public class Person : IDbItem {
   public string Name;
   public int Age;
   public object Id { get; set; }
}
...
Person p = new Person { Name = "Test", Age = 30 };
storePerson(p);
...
void storeDbItem(IDbItem item) {
   p.Id = ObjectId.NewObjectId();
   _collection.Insert(item);
}

I have attempted this with both an interface and an abstract class and in both cases only the ID is stored (which make sense, given the scope). Essentially I have an in memory data store that already implements a similar interface and I would like to drop in a LiteDB storage option without having to update external libraries that use the interface.

**Comment by intiondevelopment** [comment]
Hello, this issue is closed, but I am wondering if there is support for this scenario yet?

We got the following exception:
![image](https://github.com/mbdavid/LiteDB/assets/57911564/16114bb0-c4c3-452e-a008-4d8d59e5b7f7)

when using:
![image](https://github.com/mbdavid/LiteDB/assets/57911564/1fb396ee-d4af-4575-89a2-c37c633a4904)

When we omit the 'Id()' call, we get errors about duplicate keys.

It seems that members from inherited interfaces are not taken into account:
https://github.com/mbdavid/LiteDB/blob/d2ded92340ac78664f0b6f235bc32c9bcb513e6e/LiteDB/Client/Mapper/BsonMapper.cs#L354

A solution like this would easily fix it:
https://stackoverflow.com/questions/358835/getproperties-to-return-all-properties-for-an-interface-inheritance-hierarchy

To be backwards compatible, it might be required to add a new 'IncludeAllInterfaceProperties' setting to the BsonMapper, but if you look at it, it shouldn't be really needed: in the fluent syntax of the mapper you can use the inherited properties as expected. In the current version there is a contradiction: you can use the properties in the mapper, but it is not working at runtime.

Is this something that can be considered?
