### ISSUE TITLE
Questions : My questions about what i need to get startup to LiteDB v3.

### ISSUE THREAD

**Issue by aytacasan** [mbdavid/LiteDB#446]
Hello Mauricio,

I want to say that this is the first time to use github issues page (except yesterday testing question) and don't know about it's rules. So if i use it inconvenient way please warn me about that. Thanks for your honorable, so valuable project. It's really so simple, useful and also powerful. After read LiteDB's wiki and look at some samples on internet, still i don't understand some parts and can not start to use LiteDB in my financial project. Maybe reason of don't understand that i never use single file based no-sql solution before. I want to ask all questions here;

1. Actually LiteDB have default mapping scheme. But if we want we can overwrite this via attributes or via fluent api. Am i right? If so i'll prefer to use fluent api because attributes makes dirty my POCO classes. In your some samples you are recommending to use global static mapper and some other users overriding LiteDatabase's OnModelCreating and i can not override this in my code, there is no such a method in LİteDatabase. Reason is OnModelCreating not supporting latest release? I'm also wrote my Database class which is derived from LiteDatabase class, so what is the right way to use fluent api for mapping?

2. In your library most confused part for me EnsureIndex method. Why we have to call it? When we have to call it? If we use fluent api and specify all indexes and their details (unique or not etc.) still am i have to call it? I need details about this method usage.

3. Can i create composite index with LiteDB? For example for OrderDetails collection creating Order+Product unique composite index. If not what is your recommendation about that?

4. If my POCO class have some complex types like TimeZoneInfo, CultureInfo etc. Am i have to write extra classes for convert this data between read-write from/to data file process? I think yes because of as normal there is no such a bson data types. If so how i can write this type classes in a proper way, could you please tell me?

5. Could you please create simple examples for all relation types, for one to one, one to many and many to many. I'm so confused about that. For example i try to create one to many relation between my POCO classes and try to use include as you show one of your sample but i'm receiving an error at compiler phase.

6. I said that i'll use LiteDB on a financial project (large scale project, i hope LiteDB can handle it). Because of that i'm worry about what is your personal opinion about time series databases. Are you have any plan to write time series version of LiteDB (LiteTSDB)? Are you have any opinion about this type databases really useful or not?  especially for financial applications?

**Comment by mbdavid** [comment]
Hi @aytacasan, be welcome to Github :) I don't have any rule about issues yet. I try always response as soons as possible. First, my wiki/site are not full updated to v3, so some of your questions are about this.

1- There is no more "OnModelCreating". Now you need use LiteDatabase ctor to pass your global instance of BsonMapper (on some class that derived from BsonMapper). You can implement custom mapping just only using current BsonMapper class using `Entity<T>()` to map each type you want. I recommend always use a global instance of BsonMapper because all mappings are stored in cache, so it's better performance do not always create mapping functions.
If you want more complex rules (or create your own convetion rules) you can override BsonMapper and implement any of methods.

2- The quick answer is never. Well, almost never. It's because this method create (if not exits) an index in a document field. That was very useful in very first implementation of LiteDB (and of course, that was from MongoDB). At first version, that the only way you can create new indexes. Many versions later, it's possible create using attributes, mappings or on-the-fly, when you run any query on a field that doesnt have any index.

3- No, you can't. Composite index are not support yet (and I don't know if someday will be). It's pretty hard to do queries in composite indexes. I recomend use single column primary key with 2 fk. Your code must garantee that there is no duplicate Order+Product.

4- Yes, for this simple types (like Timestamp, Uri, CultureInfo) you must implement you own BSON value representation. You can use `BsonMapper.Global.RegisterType`. Here an example:

```
BsonMapper.Global.RegisterType<Uri>
(
    serialize: (uri) => uri.AbsoluteUri,
    deserialize: (bson) => new Uri(bson.AsString)
);
```

In this case you are implementing simple conversion from/to Uri using "string" BSON value.

5- About this, I don't know how you much you know about data model design in a document database. I recommend read this: https://docs.mongodb.com/manual/core/data-model-design/

LiteDB works like mongo in this way. When you are modeling you POCO class, you can map some field as only a reference and, when serialize, this document will not be stored as embeed document but only as a reference id. Here some testing for 1x1, 1xN and NxN.

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Database/IncludeTest.cs

After some tests I recommend use LiteDB.Shell to undersant how documents was storage.

6- About time series database: I never heard before :) I always worked in commercial applications and products that doenst need any special database data type.

**Comment by aytacasan** [comment]
Thanks for your detailed answers @mbdavid. All your answers clear for me but i want to clarify some of them;

1. I understand you clearly about mapping. Yes i want to use static global mapper like as your recommend and because of other reasons; performance and easy to use etc. But what about this;

`public sealed class Database : LiteDatabase, IDatabase
    {
        public Database(string connectionString)
            : base(connectionString)
        {
            Mapper.Entity<Customer>()
                .Id(c => c.Id)
                .Index(c => c.Name, true)
                .Ignore(c => c.Orders);

            Mapper.Entity<Order>()
                .Id(o => o.Id)
                .Index(o => o.Date, false)
                .DbRef(o => o.Customer, "Customers");
        }
    }`

Is this code have any logical error? My purpose is write clear code, give responsibility of data mapping to database class.

2. I'm very happy to hear that we don't have to call EnsureIndex nethod when we use mapping etc.. Now this is make sense for me. This must be like that unless we want to create collections at run time. I think most of the LiteDB users like the feature of on the fly index creation but i don't, at least for my current project. Is there any parameter/settings for close this feature?

3. I understand. Yes you are right develop this feature can be hard process. I'll follow your recommendation about that. I hope one day you have enough time and perseverance for develop this feature too.

4. For now very clear for me but i have to try it for my TimeZoneInfo & CultureInfo types and see the results.

5. I have serious experience about data modelling on relational databases but not about document databases. Also i noticed that my question is very generic. I'll explore your links and learn more about document database modeling. After that if i have any question, i'll try to ask more specific form.

6. Time series database quite famous in recent times. Mathematicians, statisticians, economists are using this type databases when they need analyses any data that have relation with time data. Technically time series database using time for indexing. Anyway if you develop commercial applications as your said most probably you don't need to use this type databases.

Also i asked a question with number  #444, please check it. If you need detailed info about that please inform me, so i can add extra explanation and some sample codes.

Have a nice day. God bless you!

**Comment by mbdavid** [comment]
Hi @aytacasan, lets go:

1) Do not map your entities in ctor class. This will always run in each LiteDatabase instance that you call. Try use static ctor, like:
```
public class Database : LiteDatabase
{
    static Database()
    {
        BsonMapper.Global.Entity<Customer>()....

        BsonMapper.Global.RegisterType<Timestamp>(...);
    }
}
```

2) Yes, you only create on mapper this index and never call anu query using this field, LiteDB will never create this index. I had plans to auto create all indexes on statup database, but is quit expensive do it all times. So, I suggest you to create your own procedure to "startup" your collections/indexes (and now you will need EnsureIndex to do this - becase ensureindex will create index, even you dont run any query.

5) About relations: its depend about your application. In you example, OrderDetail can be embedded list of subdocuments, becase OrderDetail dont exists without Order. But products must be a reference in OrderDetail. Like this:

```
public class Order
{
    public int OrderId { get; set; }
    public List<OrderDetail> Details { get; set; } = new List<OrderDetail>();
}

// has no Id - is embedded document
public class OrderDetail
{
    public int Quantity { get; set; }
    [DbRef("products")] // using attribute to be simple (can be via mapper)
    public Product { get; set; }
}

// 
public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public decimal Price { get; set; }
}

// when you insert an order, json will be
{
    OrderId: 1,
    Details: [{
        Quantity: 10,
        Product: { $id: 4, $ref: "products" }
    }]
}

To query an order, you always get all details (because are embedded), 
but if you want include products in result, you must run include

var q = orders.Include(x => x.Details[0].Product).FindById(1);
```

Regards

**Comment by aytacasan** [comment]
Hi @mbdavid, thanks for your time&answers.

* In my current project i'm using unity container and register my Database type singleton. So it's constructor calling one time at startup of application (at first request for database instance unity auto create one instance and hold it's reference for next request giving same instance) and disposing when user close the application. My application working user's client, single user accessing to database file and read-write data performance is so important because of that i designed like that. So still are you recommending using static constructor? If so i will follow your recommendation. More important think what is your opinion about my design (remain open data file throughout the program life cycle)?

* About creating all indexes on startup you are right, first creation of data file will be slow down for that containing many collections/indexes. Sorry still i have a relational database perspective, nor document database:) And you are also right about if developer wants to create indexes before run any query he/she can use ensure index method at startup. But what about on the fly index creation, can i block this feature?

* What i understand from your words that don't always be against embedded documents, sometimes it can be good solution vs reference documents. In my project performance very important so please tell me in your sample code, query order details (which is embedded document) will be slow down queries or will be same as it's reference document form? If you say, read/write/query performance doesn't change vs reference-embedded documents so i'll prefer to use embedded documents.

Best Regards
