### ISSUE TITLE
Which platforms does it support?

### ISSUE THREAD

**Issue by NatsXDLageg** [mbdavid/LiteDB#448]
Currently, I am trying to build for WSA in Unity, and, like other dlls, it is not compatible with the version of .NET used.
One of the problems is that some methods from System.IO don't work in .NET version of WSA.
So my question is: which platforms does it support? Specifically talking about Unity, does it support Android, IOS, WebGL?

**Comment by mbdavid** [comment]
Hi @NatsXDLageg, LiteDB v3 supports .net35 and netstandard1.4 platforms. For unity, current version of litedb seams not working because use Reflection.Emit. But, you can download for now from Unity3D branch.

I never work with unity, but as lot of users here says, it´s possible to run in any mobile platform .

**Comment by kuiperzone** [comment]
Has there been any use or testing with .Net Core or mono?

**Comment by mbdavid** [comment]
@kuiperzone, I use LiteDB only in net full, but it's compatible with net standard.
