### ISSUE TITLE
Connection string option to create empty for on Open new collection?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#451]
When a new collection if opened, LiteDB does not write a file until the first document is written.

If think this is fine by the way.

However, in my application I want to determine whether a collection has been opened (even if it has no documents). I solved this problem by writing an empty placeholder file myself, and this seems to work OK. I do have slight concerned, however, that in some future version of LiteDB it may fail to open a collection where there is an empty placeholder file because it is expecting some header information of some kind (perhaps my concern is not valid).

Would it be possible to add an a connection string option to force the creation of an initial file?

(I thought the "Initial Size" option would do this, but it doesn't apparently. It appears to default to a value based on page size anyway.)

**Comment by mbdavid** [comment]
Hi @kuiperzone, another way to solve this problem is use `EnsureIndex` in empty collection. This will create collection with no documents and adding index definition.

It's complicated call this when you "open" and collection because just `GetCollection` do not use any datafile operation. To make a clean solution it's better expose this method in LiteEngine:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/LiteEngine.cs#L152
