### ISSUE TITLE
Id restriction

### ISSUE THREAD

**Issue by OlegLevitsky** [mbdavid/LiteDB#452]
Hi there!
I am going to use LiteDB for a lot of data and I can't find an answer on the following question:
How to add more than Int32.MaxValue records? **Or** how to use unused ids (something like id=2 for collection with ids 1,3,4, ...)?
As I understand there are a few ways to solve it:
1. Create a new collection and merge all data there.
2. Create custom Id generator
3. Insert first item with id=Int32.MinValue. (ids will be MinValue, MinValue+1, MinValue+2, ...)
Am I right? is it ok to use negative ids?

**Comment by aytacasan** [comment]
Hi @OlegLevitsky,

If i understand you correctly you mean that,

* In your collections you have records count -bigger or pollibily will be bigger- than Int32.Max  value
* Also you want to re use deleted record's id values. For example already you have 3 records and their id's 1,2 and 3. if you delete second record that it's id value is 2, very next inserted recorded id must be 2.

Actually ObjectId (https://github.com/mbdavid/LiteDB/wiki/Data-Structure) is your solution, there is no any limit about it. But also you want to re-use deleted record ids, because of that you have to write your own logic with AutoId(https://github.com/mbdavid/LiteDB/wiki/Object-Mapping).

My opinion you only need to implement 2. solution which is AutoId. 1. and 3. solutions not usual and not make sense for me. All you need is the AutoId. My suggestion is create a reusable ids collection for purpose of save reusable ids for each record collection. Then in your AutoId's newId logic first check it, if there is reusable id? If so use it if there is not so send +1 value.

Also have to say that i'm newbie about LiteDB. @mbdavid please check my suggestion because i don't want to mislead other members.

Regards

**Comment by OlegLevitsky** [comment]
>  In your collections you have records count -bigger or pollibily will be bigger- than Int32.Max value
Your are absolutely right.
> Actually ObjectId is your solution, there is no any limit about it.
Well yep it looks applicable for my data.

Thanks a lot for a so quick answer! I am appreciate your help.

**Comment by aytacasan** [comment]
You are welcome @OlegLevitsky. You selected to use ObjectId then your reuse Ids problem automatically solved because there is no need to do that. ObjectId guarantee unique Ids (like Guid) for your records via it's structure parts (Timestamp, Machine, Pid and Increment).
