### ISSUE TITLE
Trying to open a non-LiteDB file is successful, at first

### ISSUE THREAD

**Issue by nmaier** [mbdavid/LiteDB#457]
File it seems that LiteDB "files" have an actual file header, that header is currently not verified.
It would help to verify the header to catch attempts to open non-LiteDB files early, so that it can be handled gracefully

## STR ##
```c#
private static void Main(string[] args)
{
  using (var writer = new FileStream("test.ldb", FileMode.OpenOrCreate | FileMode.Truncate, FileAccess.Write)) {
    var garbage = Encoding.UTF8.GetBytes("some garbage");
    writer.Write(garbage, 0, garbage.Length);
  }
  var db = new LiteDatabase("test.ldb"); // should throw here
  Thread.Sleep(1000);
  var doc = new BsonDocument
  {
    ["_id"] = ObjectId.NewObjectId(),
    ["Name"] = "John Doe"
  };
  var col = db.GetCollection("test");
  col.Insert(doc); // but only throws here
  var doc2 = col.FindById(doc["_id"]);
}
```

## Expected ##
`LiteDB` should verify the file header and throw early, when the `LiteDatabase` instance is first created. Empty files should not throw, of course.

## Actual ##
`System.Exception: Invalid pageType` is thrown only in the `.Insert`, which is not only rather late.

**Comment by mbdavid** [comment]
LiteDatabase open datafile only when you made your first use. It's nice because sametime your logic could be initializa database but dosent use and you open/close a file (expensive resource) and not used. If you want test your datafile as you open, just call `db.Engine` or you can use `LiteEngine` - low data level access.
