### ISSUE TITLE
v3 db file corruption when interrupting bulk insert 

### ISSUE THREAD

**Issue by far100** [mbdavid/LiteDB#486]
Hi.
I have a console application that make a bulk insert with journaling and without transaction. during the run I just press control-c. the db file became unaccessable and  casting error from empty page to header page is thrown.

a- is this a bug or expected behaviour?
b- how can I recover the database after that? assuming a corruption happened after deployment for this reason or any other reasons.

thank you a lot

**Comment by mbdavid** [comment]
Hi @far100, yes, it's excpected. In Storage, files are saved in chuncks document. Transactions are not supported in storage because use too many memory.

If you check you file and are with Length = 0, an error occurs during write. But, database datafile are not corrupted, only this file (must be excluded)

**Comment by far100** [comment]
thank you for your quick response.
and sorry for my misleading issue title.

the bulk insert is for strongly typed classes and not file storage.

**Comment by mbdavid** [comment]
I just update nuget with a new version that check if your are using FileStorage in transaction. If you try now, you will get an exception showing this.
