### ISSUE TITLE
Backward compatibility between 3.0.0 release and beta 2 version

### ISSUE THREAD

**Issue by Vakterman** [mbdavid/LiteDB#514]
Hi.
It is possible there is some discussion about it. But i didn't find it.
Initialize method for objects in litecollection has been changed as shown below:
For beta 2 version:
 Expression.Lambda<CreateObject>(Expression.New(type)).Compile() 
For release version
 var dynamicMethod = new DynamicMethod("_", type, (Type[])null);
 var il = dynamicMethod.GetILGenerator();
 il.Emit(OpCodes.Newobj, type.GetConstructor(Type.EmptyTypes));

It is very well, but it is fatally  for internal or non-public types. Exception occured during reading collection from litedb.

**Comment by mbdavid** [comment]
Hi @Vakterman, changed because there are some problems using Expression in .net35 (I can't remeber now). Now I have 2 implementations: one for net35 (using emit) and one for netstandard (using expression).

I will review this and test if it's possible use CreateClass/CreateStruct use only Expression.

**Comment by mbdavid** [comment]
Hi @Vakterman, current HEAD version now complete remove Emit from solution in .net35 (I made a single solution for .net35 and netstadnard). I forgot to link to his issue. Take a look there

**Comment by Vakterman** [comment]
Thank you very much!
It works fine!!!
