### ISSUE TITLE
Nested Includes, how to query?

### ISSUE THREAD

**Issue by freezy** [mbdavid/LiteDB#561]
This was apparently done in 3.x, yet I haven't found an example of it in the Wiki or any of the issues.

```c#
public class Book
{
    [BsonId] public string Id { get; set; }
    public List<Author> Authors { get; set; }
}

public class Author
{
    public string Role { get; set; }
    [BsonRef("users")] public User User { get; set; }
}

public class User 
{
    [BsonId] public string Id { get; set; }
    public string Name { get; set; }
}
```

I want to query books and get the full User object. How is this possible? I've tried:

1. `books.Include(x => x.Authors[0].User).FindById(id);`
2. `books.Include("Authors.User").FindById(id);`

Both return only the user's `Id` (i.e. no inclusion). Any hints or suggestions would be appreciated.

**Comment by mbdavid** [comment]
Hi @freezy, there is no nested includes for List. In this case it´s better use `Include(Action<T>)`, so you can define your function, likes:

`books.Include(x => x.Authors.ForEach(z => z.User = users.FindById(z.User.UserId))`

**Comment by freezy** [comment]
Thanks for the quick response! Would this be a possible feature in the future?

**Comment by mbdavid** [comment]
I tried to this but was not easy to be done because. In this case, need be deserialized many subdocuments per document and it´s not easy to detect this. Thats why I added this `Include` using an `Action`.

**Comment by freezy** [comment]
Alright, thanks for the info!

**Comment by Tochnia** [comment]
Hy,
I try to achieve the same thing, but I didn't get it to work. I already tried the example above with the suggested function (but I guess it should be z.User.Id instead of z.User.UserId):
books.Include(x => x.Authors.ForEach(z => z.User = users.FindById(z.User.UserId)) 

But I get the error message (Cannot convert lambda expression to 'string' because it's not a delegate type)

Is this sample still valid with the version 4.1.4.0?

**Comment by HernanMartielli** [comment]
Could anyone solve this?
