### ISSUE TITLE
Id property is not recognized when inserting a POCO

### ISSUE THREAD

**Issue by ThomasWeiss** [mbdavid/LiteDB#6]
Looking at [the source code](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/BsonSerializer.cs#L150), it looks like it's now mandatory to have the `BsonId` attribute on the Id property, even if it's named `Id`. Is this intended?

**Comment by mbdavid** [comment]
Hi Thomas, it's a serialization problem. I remove "primary key" from object before serialize object (the key value are stored in a another space from the rest of document [see here](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Storage/Structures/DataBlock.cs#L38)). When I deserialize a data bock, I inject key value on document again [see here](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/BsonSerializer.cs#L45).

The ploblem occurs because I can remove a property from serialization using fastBinaryJson (an external library). The only way is use an attribute for that (BsonId). If you remove comments it's will work, but try open on Lite.Shell and run a "find" command. Results "_id" key AND Id (or MyEntityId) property on document.

I have two options:
1 - Change fastBinaryJson to remove this Id property with any attribute
2 - Write my own serialization - it's nice option, but it's not an easy job.

I'm doing some tests on "dev" branch. I will keep this issue open to post changes.

**Comment by ThomasWeiss** [comment]
Hi Mauricio,

Thanks for your explanations. Whatever path your choose, make sure the documentation is up-to-date (right now, it states that a POCO with an `Id` property will be accepted, which is wrong).
Very nice library btw, can be useful in many cases.

**Comment by mbdavid** [comment]
Hi Thomas, you are rigth: documentation is not up-to-date. I will fix this when publish new version (next weekend).

**Comment by mbdavid** [comment]
Fixed in v0.9.0 - Now supports `Id`, `<Classname>Id` and `[BsonId]`
