### ISSUE TITLE
KeyNotFoundException during deleting from FileStorage

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#607]
```
=========================
Exception Information
=========================
Message: The given key was not present in the dictionary.
Source: mscorlib
TargetSite: TValue get_Item(TKey)
HelpLink: 
Type: System.Collections.Generic.KeyNotFoundException
Place: 1
Stack:
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at LiteDB.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
at LiteDB.QueryEquals.<ExecuteIndex>d__2.MoveNext()
at LiteDB.LiteEngine.<>c__DisplayClass50_0.<Delete>b__0(CollectionPage col)
at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
at LiteDB.LiteEngine.Delete(String collection, Query query)
at LiteDB.LiteEngine.Delete(String collection, BsonValue id)
at LiteDB.LiteStorage.Delete(String id)
```

**Comment by tripathv** [comment]
Hi,
I am getting the same issue. I am using v4 beta 2 but still having the same issue.
"   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at LiteDB.IndexService.<FindAll>d__13.MoveNext()\r\n   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___0>d.MoveNext()\r\n   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)\r\n   at LiteDB.LiteEngine.<Find>d__9.MoveNext()\r\n   at LiteDB.LiteEngine.<Find>d__13.MoveNext()\r\n   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()"

I had an issue where I started getting this error when adding an item, since then, reading is throwing the above issue

f1ab0a9e-a309-46cd-944c-59686fbd55df | 10/10/2017 12:56:22 AM | EXCEPTION: Exception of type 'System.OutOfMemoryException' was thrown.,    at LiteDB.BasePage.WritePage()    at LiteDB.TransactionService.Commit()    at LiteDB.LiteEngine.Commit()    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)    at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)    at LiteDB.LiteCollection`1.Insert(T document)    at Credience.RiskManager.UI.Services.DataService.AddTradeAuditLog(TradeAuditLog tradeAuditLog) | DataService.AddTradeAuditLog
-- | -- | -- | --

**Comment by mbdavid** [comment]
Hi @tripathv, are you using v4 to create your datafile or your datafile cames from v3.x? If are from v4, can you paste you code to check this?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
