### ISSUE TITLE
commit bug

### ISSUE THREAD

**Issue by tbdbj** [mbdavid/LiteDB#62]
not all data written after commit.
Bug code:
```
const string tableName = "users";
const int n = 100;

using (var db = new LiteDatabase(@"C:\5\test.db"))
using (var db2 = new LiteDatabase(@"C:\5\test.db"))
{
	db.BeginTrans();
	db.DropCollection(tableName);
  var users = db.GetCollection(tableName);
	for (int i = 0; i < n; i++)
	{
		var doc = new BsonDocument();
		doc["_id"] = i;
		users.Insert(doc);
	}
	db.Commit();

	users = db2.GetCollection(tableName);
	Assert.AreEqual(users.FindAll().Count(),n);
}
```
without breakpoint after db.Commit() the test will failed (Assert.AreEqual(users.FindAll().Count(),n)).

**Comment by mbdavid** [comment]
Hi @tbdbj, this bug is a dirty read problem. When you open 2 instances, at this time there is no collection in both. You create in one e immediate try use in another but all in memory vars has no this collection.

LiteDB implements a solution that try to avoid this problem. Please see:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Storage/Services/TransactionService.cs#L132

Take a look, there is a hard coded "1s" timer to avoid always read header page before any read operation (if you put a breakpoint works because more than 1 second will pass). Try comment line 138 and test again.

**Comment by mbdavid** [comment]
Hi @tbdbj, just to know, current `master` branch version now fix this problem.
