### ISSUE TITLE
String case sensitive in LiteDB query

### ISSUE THREAD

**Issue by Aimeast** [mbdavid/LiteDB#658]
I have questioned at stackoverflow https://stackoverflow.com/q/44184505/1011174 1 mouth ago

In various environment, the user name is case insensitive. We query `admin` equal to `ADMIN`. I have searched `LiteDB` called `CompareTo` to compare two objects that I can't find a point to make string compared as case insensitive.

The code in `QueryEquals.cs`

    internal override IEnumerable<IndexNode> ExecuteIndex(IndexService indexer, CollectionIndex index)
    {
        var node = indexer.Find(index, _value, false, Query.Ascending);

        if (node == null) yield break;

        yield return node;

        if (index.Unique == false)
        {
            // navigate using next[0] do next node - if equals, returns
            while (!node.Next[0].IsEmpty && ((node = indexer.GetNode(node.Next[0])).Key.CompareTo(_value) == 0))
            {
                if (node.IsHeadTail(index)) yield break;

                yield return node;
            }
        }
    }

The propositional we can case insensitive

    using (var db = new LiteRepository("lite.db"))
    {
        db.Insert(new User { Name = "John" });
        var user = db.Query<User>()
            .Where(x => x.Name == "JOHN")
            .FirstOrDefault(); // proposal return John
        var fail = db.Query<User>()
            .Where(x => string.Equals(x.Name, "JOHN", StringComparison.OrdinalIgnoreCase))
            .FirstOrDefault(); // throw exception
    }

Another consideration, it is a possible to execute lambda expression in LiteDB without conversion by visitor?

**Comment by mbdavid** [comment]
Hi @Aimeast, you can't change how data is storaged in index because it's will fail to found inside index. When any solution support ToUpper (or any other function) during query no index are used.

You can store lowercase inside your index and than always query lowercase (or uppercase).

// creating index in lower case
`db.Mapper.Entity<YouClass>().Index("user_lower", x => x.Username.ToLower());`

and search using.

`var result = col.Find(Query.EQ("user_lower", username.ToLower());`

**Comment by trichling** [comment]
Hi,

this does not seem to work for existing documents (see also #509).

Consider the following unit test which fails for me:

`[TestMethod]
        [TestCategory("Unit Test")]
        public void LiteDbArticleRepository_CaseInsensitiveSearch_NoIndexForExistingDocuments()
        {

            using (var db = new LiteDatabase(@"Filename=data\articleDatabase\IndexExisitingDocs.db"))
            {
              
                var articles = db.GetCollection<TestArticle>("articles");

                articles.Insert(new TestArticle() {Id = 1, Bezeichunung = "Bierwurst"});
                articles.Insert(new TestArticle() {Id = 2, Bezeichunung = "Wurst mit Bier"});
                articles.Insert(new TestArticle() {Id = 3, Bezeichunung = "Schinkenbier"});
                articles.Insert(new TestArticle() {Id = 4, Bezeichunung = "Pommes mit Sauce"});

                var all = articles.FindAll();
                Assert.AreEqual(4, all.Count());

                var bierArticles = articles.Find(Query.Contains("Bezeichunung", new BsonValue("bier")));
                Assert.AreEqual(1, bierArticles.Count());

                db.Mapper.Entity<TestArticle>().Index<TestArticle>("BezeichnungLower", a => a.Bezeichunung.ToLower());
                **articles.EnsureIndex("BezeichnungLower");**

                var bierLowerArticles = articles.Find(Query.Contains("BezeichnungLower", new BsonValue("bier")));
                **Assert.AreEqual(3, bierLowerArticles.Count());**

            }

 public class TestArticle
    {

        public int Id { get; set; }

        public string Bezeichunung { get; set; }


    }
`

Please notice that I am adding items before definig the index. Even the call to EnsureIndex does not help here. 

Am I missing something? Is there a way to apply a virtual property index to existing documents?

Kind regards,
Tobias.

**Comment by mbdavid** [comment]
Hi @trichling, it's will not work for existing documents because this virtual field index store data in each document. If you create after is not present in already stored documents.

In this case, you have a changed version of your schema. I recommend you do manage this change after open database using `db.UserVersion` to track changes. In this case, you need update all your documents adding this new "column" to be indexed.

**Comment by trichling** [comment]
Hi Mauricio,

thanks for clarifying. At least I know I am not doing anything wrong.

Kind Regards,
Tobias.

Von meinem iPhone gesendet

Am 08.08.2017 um 10:55 schrieb Mauricio David <notifications@github.com<mailto:notifications@github.com>>:


Hi @trichling<https://github.com/trichling>, it's will not work for existing documents because this virtual field index store data in each document. If you create after is not present in already stored documents.

In this case, you have a changed version of your schema. I recommend you do manage this change after open database using db.UserVersion to track changes. In this case, you need update all your documents adding this new "column" to be indexed.

**Comment by mbdavid** [comment]
Hi @trichling, after read this I'm thiking in create "index function transformation" that can by applied on index before store. Some basics function could be "lower", "upper", "toInt", "trim" that can be easy to implement. Using this kind of definition on index (not on field) I can apply for all documents, including exist documents.

I will think better and write a propose about this.

**Comment by mbdavid** [comment]
Done in v4 beta! Now you can write expression functions in index definition.

`col.EnsureIndex(x => x.Name, false, "LOWER($.Name)")`

After you can search using lower case.
