### ISSUE TITLE
Using LiteDB on Azure Blog Storage

### ISSUE THREAD

**Issue by fsryckewaert** [mbdavid/LiteDB#683]
Anyone has experience using LiteDB on Azure Blob Storage? I've seen this [link](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-blobs) on how to start using Blob Storage but wonder how to work it into LiteDB (please don't suggest moving to Cosmos DB).

Thanks!

**Comment by mbdavid** [comment]
Hi @fsryckewaert, you can't use LiteDB in blob storage (or any other storage like that) because this king of storage offers only support to upload/download the as a whole.

It's possible build a implementation of IDiskService to access your remote data. But I do not believe that would work well. Depending on your solution, it may be more interesting to store the local disk and send the whole file, from time to time, to Blob Azure

**Comment by xied75** [comment]
@fsryckewaert I would like to know your business requirement here if you are happy to share?

**Comment by mbooh** [comment]
Ah, sorry. Just posted a new question on this issue. So I guess I have to find another solution to get this to work in Azure.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
