### ISSUE TITLE
LiteDB (3.1.2) "Process cannot access the file"

### ISSUE THREAD

**Issue by bobmcallan** [mbdavid/LiteDB#691]
Upgrading from 3.1.1 to 3.1.2 has resulted in significant file blocking issues. The database seems to hold (?) the database file from previous requests/code. 

**Application/Details**
Description: Windows API Service. 
Code: C# .Net 4.5
OS: Windows 10 (Pro)
Connectionstring: "filename="c:\...*.db" (No Options)

Same code works fine in 3.1.1.

eg. Simple Count.  
using (var db = new LiteEngine(model.dbFullName, false))
                    {
                        return db.Count(model.CollectionName, query);
                    }

I've attempted to alter the code to use LiteEngine / LiteRepo etc. same result.

Bob

**Comment by testbench** [comment]
I have also experienced this in 3.1.2, I will downgrade to 3.1.1 and see if the same happens for me.

**Comment by nlap** [comment]
Seeing this too. Had to drop back to 3.1.1. I have multiple processes reading & writing. 3.1.2 shows errors such as:

`The process cannot access the file '[...].db' because it is being used by another process.`

`Exception at System.IO.__Error.WinIOError(Int32, System.String) at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean) at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32) at LiteDB.FileDiskService.Initialize(LiteDB.Logger, System.String) at LiteDB.LiteEngine..ctor(LiteDB.IDiskService, System.String, System.Nullable1<System.TimeSpan>, Int32, LiteDB.Logger) at LiteDB.LiteDatabase+<>c__DisplayClass11_0.<.ctor>b__0() at LiteDB.LazyLoad1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value() at LiteDB.LiteCollection..... etc`

Let me know I can be of help debugging.

**Comment by mbdavid** [comment]
This errors could be because are using netstandard version.  Netstandard doesn't support multi instances (there is not FileStream.Lock method). If you are using full net framework, prefer net35 version.

**Comment by testbench** [comment]
I have downgraded to v3.1.1 and using the same .net framework I don't get these errors, so it seems specific to v3.1.2

**Comment by mbdavid** [comment]
Yes, in 3.1.2 .csproj was changed to VS2017and all version after NET3.5 was "converted" to netstandard... I'm fixing this in next version

**Comment by bobmcallan** [comment]
Upgraded to 3.1.4 - All good. Thanks

**Comment by johna1203** [comment]
I will comment here because the error is similar.

I am using the LiteDB 5.0.0-alpha2 and, I get the error below using multithread, could someone guide me how can I solve this?
"The process cannot access the file 'C:\Test-log.db' because it is being used by another process."

Thanks,
