### ISSUE TITLE
Lazy loading of embedded documents

### ISSUE THREAD

**Issue by stupkad** [mbdavid/LiteDB#707]
Hi,

I am evaluating LiteDb for a commercial c# application as application file format, I really like LiteDb because it is super fast, so far very stable and easy to use.

I have to deal with approx. 1000 instances of an object A, where each object of type A holds some header information and additionally an array of 100 other objects of type B. These 1000 objects of type A have to be presented the user in a listview, but I would like to load the details (array of type B) on demand to avoid runtime and memory issues.

Is there an out of the box solution for lazy loading of embedded documents? Not a big deal implementing this for my own, but perhaps this already exists an can be reused.

Thanks,
Dietmar

**Comment by mbdavid** [comment]
Hi @stupkad, in this case, is not better store this documents in 2 separate collection? In collection A you just add your ListView documents. And in a second B collection you store your second document with a link to document A. 

This option is recommended if you array of B are large documents. It's will avoid load all to memory.

You can use also DbRef in this array and than use Include in query to load, but for 100 array items, I do not recommend because this. You will get much more performance no tracking all IDs in this array but add reference on B document to A document.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
