### ISSUE TITLE
about null value

### ISSUE THREAD

**Issue by codeyu** [mbdavid/LiteDB#709]
class:
```cs
public class Person
 {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public DateTime? Birthday { get; set; }
  }
```

Test:
```cs
var col = db.GetCollection<Person>("Person");
col.Insert(new Person { Fullname = "John" });
col.Insert(new Person { Fullname = "Doe" });
col.Insert(new Person { Fullname = "Joana" });
col.Insert(new Person { Fullname = "Marcus" });
```
delete result:
```cs
var delResult = col.Delete(x => x.Birthday < DateTime.UtcNow);
```
OR
find result:
```cs
var findResult = col.Find(x => x.Birthday < DateTime.UtcNow);
```
I think `delResult = 0`  or `findResult.Count() = 0`, but result of test is `delResult = 4`  or `findResult.Count() = 4`.
Is it a bug?

**Comment by mbdavid** [comment]
Hi, that happend because `null` are a type of value (like int or string). And, when you compare 2 diferent types (like DateTime with null) LiteDB comprare data type order only. And null are less than Date. This will happend if you add another datatype too, like

`db.Engine.Insert("col", new BsonDocument { ["_id"] = 5, ["Fullname"] = "Demo", ["Birthday"] = 5 });`

So, when I compare `5` with `DateTime.Now` I just compare order of each data type:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/BsonType.cs

I will take a look on how MongoDB resolve this and return here.

**Comment by mbdavid** [comment]
You right @codeyu, it's wrong result in LiteDB. Thats mongodb results:

```
> db.col1.find()
{ "_id" : 1, "a" : 1 }
{ "_id" : 2, "a" : 2 }
{ "_id" : 3, "a" : null }
{ "_id" : 4 }
{ "_id" : 5, "a" : "str" }

> db.col1.find({a:1})
{ "_id" : 1, "a" : 1 }

> db.col1.find({a:{$lte:1}})
{ "_id" : 1, "a" : 1 }

> db.col1.find({a:{$lte:2}})
{ "_id" : 1, "a" : 1 }
{ "_id" : 2, "a" : 2 }

> db.col1.find({a:null})
{ "_id" : 3, "a" : null }
{ "_id" : 4 }
```

Mongo does not return different types when using `>` `<`

It's not too much clear to me after read this:

https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#bson-types-comparison-order

**Comment by codeyu** [comment]
Thank you for your job:)
