### ISSUE TITLE
Question. Right way to use and thread safety.

### ISSUE THREAD

**Issue by VoronFX** [mbdavid/LiteDB#725]
Hi!
There is nothing in docs about how to use LiteDB from multi threading point of view. For example in some ASP.NET web app.

1. Should I create one singleton of LiteDB or better to create instance for each request/controller. (Concurrency of LiteDB instances).
2. Can I work with one instance from several threads simultaneously, at least for read scenarios or each thread should have own instance?  (Concurrent access to one instance).
3. Any other not obvious caveats?

Please, can you clarify these things so I can design proper use-architecture and synchronization.

**Comment by mbdavid** [comment]
Hi @VoronFX, quick answer: to web/mobile use a single instance across all thread for both read/write operations. If it's possible, use Exclusive mode too in connection string. 

But I also write this wiki page about this:

https://github.com/mbdavid/LiteDB/wiki/Concurrency

And I recommend you to use v4 beta because there are some issues in v3.x about single instance use.

**Comment by VoronFX** [comment]
So no additional synchronization needed. Awesome!

> Single instance is much faster ... and has almost no cache re-use

Didn't understand about cache. Did you mean it will hit cache more cause of shared instance or it will not use cache cause it is the only who uses file?

**Comment by mbdavid** [comment]
I fixed my text. 

## Recommendation

Single instance is much faster than multi instances. In multi instances environment, each instance must do expensive data file operations: open, lock, unlock, read, close. Also, each instance has its own cache control and, if used only for a single operation, will discard all cached pages on close datafile. In single instance, all pages in cache are shared between all read threads.

If you application works in a single process (like mobile apps, asp.net websites) prefer use a single database instance and share across all threads.

You can use `Exclusive` mode (in connection string). Using exclusive mode datafile will avoid always checks header page to check if has any external change. Also, exclusive mode do not use Lock/Unlock in file, only in memory (using `ReaderWriterLockSlim` class).

**Comment by VoronFX** [comment]
Thank you! Now things are much clearer!

**Comment by diegonunesbr** [comment]
There are some sample to use Single Instance?

**Comment by cavevs** [comment]
Some example code would be very useful...thanks

**Comment by marekvse** [comment]
This is really terrible. I've spent so much time trying to figure out how to use the single instance from multiple threads. An example would really be helpful. I am forced to use the shared mode since in the exclusive mode I get timeouts after the first write.
Also, there is quite bit of confusion about what the connection string should look like, which is possibly the reason for this not working for me. Is it now "Mode=Exclusive" or is it "Connection=Exclusive" or does capitalization matter and it is "mode=exclusive"... Or is it "mode=direct" as found on another page.????? 

Some guidance with a complete example similar to the one in Getting Started here (https://www.litedb.org/docs/getting-started/), but for the "direct/exclusive/or whatever it is called" mode, would be very helpful.

I hope you can help soon. I'm sure it would be a help to many.

**Comment by lbnascimento** [comment]
@marekvse If you're sharing a datafile between multiple **processes**, you have to use shared mode. However, direct mode should have no issues in multithreaded mode.

Are you using v5.0.4? There were some issues regarding timeouts in the previous version, but they were fixed in v5.0.4.

Also, keywords in the connection string are case-insensitive. For more info, check [the documentation](https://www.litedb.org/docs/connection-string/).

**Comment by marekvse** [comment]
@lbnascimento Hi, I only noticed your reply in my inbox now so I apologize for my delayed reaction. Thank you for the reply. However.. :(
I'd really appreciate if you could give an example of the connection string with the Direct setting. I think that it would be great for many others if you could update the documentation page you shared a link to in your reply above with it since even there it says "LiteDB offers 2 types of connections: Direct and Shared" and yet the table of Options above it says "Connection type (“direct” or “shared”)". So which is it - "direct or Direct". Adding just one more example under the "Example" heading there containing that setting would solve the confusion.

As for the version, I'm using the LiteDB database in a multi-targeted project that has to support .NET v4.0, which apparently any of the revisions higher than 5.0.0 does not support. So I'm currently pushed to use that version and cannot upgrade. Is there any chance you could return the next revision to be able to support .NET v4.0 again?

**Comment by lbnascimento** [comment]
@marekvse .NET Framework v4.0 support was dropped because it was getting increasingly difficult to mantain code for it, a lot of API calls that we needed were not supported. Unfortunately there are no plans to support it going forward.

**Comment by sunnyatticsoftware** [comment]
what about concurrency recommendations for version 5.0.8+?

**Comment by marekvse** [comment]
@lbnascimento OK, I understand that support for lower versions of different software is bound to end at some point and have to accept it in this case. However, let me ask this: If there was a bug with concurrency in 5.0.0, is there any chance that you could make a revision incorporating the fix for that bug in that version, thus helping me keep the .NET 4.0 support (which I must) and at the same time make my code run much faster being able to use the Direct setting?

Also, I did ask twice before but have not received a satisfactory answer from you yet and it seems @sunnyatticsoftware may be pointing it out above too... Could you please spell out exactly in the form of an example connection string what the word and correct capitalization for the "Direct" setting is please?
It would probably also be useful if you could state whether that form was valid for all prior versions or from which version it actually is valid. Thanks.

**Comment by lbnascimento** [comment]
@marekvse Both keys and values in the connection string are case insensitive, so any capitalization should work.

What version of LiteDB are you currently running? As far as I know, .NET Framework v4.0 was only supported in LiteDB v4. v4 is still supported and it is our intention to provide bug fixes for it (no new features will be added, though).

**Comment by lbnascimento** [comment]
@sunnyatticsoftware The recommended way to use LiteDB v5.0.x is to use direct mode and share an instance of `LiteDatabase` between all your threads (use a singleton if necessary). If you need multi-process support, use shared mode.

**Comment by marekvse** [comment]
@lbnascimento Thank you for the clarification. I think that maybe I did not think about the obvious singleton need when I was trying to make that work so thank you for pointing that out as well.

As for the connection string I'd like to suggest to you, if you can, to update the documentation's db connection page (https://www.litedb.org/docs/connection-string/) which currently says: Key = "Connection", Description = "Connection type (“direct” or “shared”)" and Default Value = "direct", which, if they are case-sensitive as you previously said are therefore wrong and may be thus causing unnecessary trouble to many other people if they are supposed to be "Shared" or "Direct" instead of "shared" or "direct".

**Comment by marekvse** [comment]
@lbnascimento Oh, and regarding the version I'm running. I double checked now and it is 5.0.0. Though Nuget does not say for that particular version which framework versions it supports. It actually does not say anything in the description or dependencies section. But you are probably right in saying that 5.x does not support .NET 4.0. It's been a while since I was coding that part of the project and forgot that for .Net 4 I actually used a much less capable custom in-memory solution do do the most important stuff the LiteDB is doing in the higher-targeted versions of .NET.
I'm not sure then why Nuget previously let me use the 5.0.0 version of LiteDB but wont update to any higher than that saying that those versions do not support net40. But it may be that I originally started three different single-target projects and later unified them to a single multi-targeted one, even though I'm pretty sure it was before even starting to use LiteDB in it. In any case, this gave me an idea right now to find out if I can force Nuget to install despite having one of the targets lower then required. It turns out I can add `<PackageTargetFallback>net451;dotnet5.6;portable-net45+win8</PackageTargetFallback>` right under the first `<PropertyGroup>` before the `<TargetFrameworks>` and that let me upgrade to 5.0.8. So thanks for asking again about the version I use and pointing out that 5.0.0 already did not support net4. I think that I am now all sorted. Will implement the singleton pattern tomorrow probably so will know for sure if it works then. But things now finally seem pretty clear so I'm confident all will work finally as expected.

**Comment by marekvse** [comment]
Well, I finally got around to update my code to use the Direct connection. 
As I read the posts again I noticed that you @lbnascimento actually say "case INsensitive", not "case sensitive" as I read it. So you either fixed your mistake or it was me reading it wrong the first time. If that is the case I apologize for that.

I'm happy to report that the code now works with the Connection=Direct. I did not have to do any other change than in the connection string and removing the `using (var db = new LiteDatabase(_Connection))` around my db access statements and uncommenting my readonly property to return the "db" singleton instead. So I'm not sure whether I never tried the "Direct" or if it is that I upgraded from 5.0.0 to the latest version the last time I responded, but this time it all works as expected compared to before, when it was not with exactly the same code changes. I would have for sure tried at least "Connection=direct" but it still did not work. Well, it works with "Direct" so I can finally be happy and am not going to even try "direct", which, according to you, should make no difference anyway. Maybe it did in v5.0.0 - I can't be sure now. All good now finally. Thanks for the help.
