### ISSUE TITLE
Save Storage Space - Questions

### ISSUE THREAD

**Issue by farangkao** [mbdavid/LiteDB#770]
While doing many tests with my Data and LiteDB (and i love it!),
i noticed the follow (may not be true):

- If using a **bool?** Value, and for most entries the Value is null, it needs much less Space then using a **bool** with most of the Values as 'false'  (it seems that if a value is Null it won't be saved in the file, but if it's the default value, such as 'false' or '0' it will be saved and therefore needs space)

- If using [BsonField("short")] for a Property with a long property Name such as "ShortWrittenPropertyName", it seems to also make a bigger Impact on File Size.

Are my assumptions correct, and if so, is there a way to solve this without 
  a) make all Types Nullable, to save Space ,even if for the program logic it's not really needed
  b) Rename all Properties or use BsonField to shorten the Names

Would be nice if there was at least a Setting like BsonMapper.Global.EmptyStringToNull
to automate this process.

In my tests the result have varied in the Mbytes of Data, on first glance this might not be much, but when you have to distribute the data over a network to multiple users , the total amount of space used is important (The difference is also visible after zipping the .db files)

**Comment by mbdavid** [comment]
Hi @falahati, to answer your questions:

1) Yes, when a field value is null, by default, they are not serializable. IT's can be changed using `BsonMapper.Global.SerializeNullValues = true`. But all valid values are serializable.
2) About short names: yes, it's reduce a lot of spaces because for each document, BSON serialization (like JSON) needs serialize field name too.

It's possible, in both cases, do changes in `BsonMapper` to use as you want. For this, use:

```
BsonMapper.Global.ResolveMember = (type, memberInfo, mapped) =>
{
// you can change FieldName and override Get/Set methods in mapped
}
```

But remember, when you change your document serialization, you must respect this new rules to query when using shell/BsonDocument only, like: `db.Find("mycol", Query.EQ("small_name", 12))`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
