### ISSUE TITLE
Reordering Collection in Database

### ISSUE THREAD

**Issue by MonolithModular** [mbdavid/LiteDB#793]
Is there anyway to reorder the collection within the database? I have several document collections that are names. I want the document collections to be in alphabetical order- or any order for that matter- starting with the 3rd collection. Is that possible?

**Comment by mbdavid** [comment]
Do you want order "collections names" or "documents inside a collection"?

**Comment by MonolithModular** [comment]
I want to order the collection names. Right now I'm creating a database that has a different document collection per name. I'm not sure if that is the best way to create a calendar database. But anyway, I'm using a display order that is based upon the chronological order of document collections. So, I would like to reorder the document collection inside the database so that I don't have to reorder them outside of the database.

**Comment by mbdavid** [comment]
There is no way to re-order collections because collection names are stored inside a `Dictionary<string, uint>`. Here the code when a collection are created:

```C#
// get new collection page (marked as dirty)
var col = _pager.NewPage<CollectionPage>();

// add this page to header page collection
header.CollectionPages.Add(name, col.PageID);

col.CollectionName = name;

// set header page as dirty
_pager.SetDirty(header);

// create PK index
var pk = _indexer.CreateIndex(col);

pk.Field = "_id";
pk.Expression = "$._id";
pk.Unique = true;
```

In this code, `col` are physical collection page (that contains name), but also are added into Header page (page 0) only page-name and page-id. When you call "GetCollectionNames", litedb uses only page header dictionary to return this collections names.

If you need keep this order, I recommend you use a special collection with documents and each document with your collection name and a order field.

**Comment by MonolithModular** [comment]
That's a fantastic idea! Thanks!
