### ISSUE TITLE
Initial Size Issues and DataFile Unexpectedly Shrinking

### ISSUE THREAD

**Issue by bbunderson** [mbdavid/LiteDB#799]
This looks like an amazing project. We are looking at switching out a bunch of our apps and services to use this library. 

We are doing performance testing and in once scenario we download many files and store using FileStorage.Upload. We have used/tested various apps and usually "growing" the database file add unneeded overhead. 

Ultimately we want the file to stay a certain size. We were looking at setting the "initial size" of the database, but it never really creates the initial size correctly. We  went ahead and manually created the FileDiskService and use the SetLength method. It then properly creates the file, but as soon as we upload anything to the FileStorage or even run EnsureIndex...it immediately shrinks the datafile. We have journaling turned off, but it seems like the shrink may have something to do with the journal in the new 4.X version.

**Comment by mbdavid** [comment]
Hi @bbunderson, as soon I was reading your issue I remember that this problem can occurs because my new change about use journal file inside same data file (at end of file). Initial size only "create" file with NN file length, but not allocate this space with empty pages. After first insert, file is resized to original size (in initial database, resize to first real size).

I will add this to next version, use Initial Size with created empty pages. Thanks

**Comment by bbunderson** [comment]
Thanks. We are very interested in the project. We would like to contribute anyway possible. This may be a little more complex to solve...since we are new to the project, but let me know if you need help with any easier things.

**Comment by mbdavid** [comment]
Hi @bbunderson, thanks for using LiteDB. If you want contribute, you can tell more about where/how do you use LiteDB when you finish your project. I always good to know when LiteDB is useful and where need be improved.
