### ISSUE TITLE
Question - Different Encryption Algorithm

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#814]
hi again @mbdavid, it's always a pleasure to talk to you.

Quick question: Is it possible to change the encryption algorithm for litedb? If the answer is yes, how? can you provide a quick example how this can be implemented?

Not the algorithm itself, just how to achieve this purpose.

thanks a lot.

regards,

[],

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, it´s always good to know dev are keep using LiteDB :)

Encryption, in LiteDB are based only in this class: https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Utils/AesEncryption.cs

Works with a simple password and salt (bytearray). All pages (except HeaderPage - PageID = 0) are encrypted using this "Encrypt"/"Decrypt" methods. Its important encrypt output keep same input size (4096 bytes)

But there is not way to change because there is no interface to implement. You need change in code base.

**Comment by rmszc81** [comment]
Sorry for answering so late.

As we say in brazil "correria".

It'll be awesome if someday you expose an interface for us to implement our own cryptography algorithm in LiteDB but, for now, what you implemented is more than enough.

Thanks a lot.

Regards,

[],

@rmszc81
