### ISSUE TITLE
Make Extensible - Leverage .NET Core 2.0 for Performance

### ISSUE THREAD

**Issue by bbunderson** [mbdavid/LiteDB#817]
I was thinking that there could be some massive performance benefits of leveraging .NET Core 2.0 on things like System.IO and Encryption. 

I think the library is perfect like it is as a single DLL for lots of applications, but I was looking and it could be easily made extensible...especially since it already supports .net standard 2.0. If the BasePage and exceptions could be made Public instead of Internal, it would allow the ability to create a .NET Core 2.0 FileDiskService by implementing the current IDiskService. 

I think that .NET Core 2.0 would provide the most improvement in the File IO, but it could probably be used to "extend" encryption also. 

Thoughts?

**Comment by mbdavid** [comment]
Hi @bbunderson, NET Core 2 implements Net Standard 2. This standard are supported in LiteDB v4 (there are a compilation for netstandard 1.3 and 2.0). So, I beleave if you using LiteDB in NET Core, you are using System.IO implementation for this version.

IDiskService can be implemented without access to BasePage (or any other pages). Disk service is a lower layer and is the only "file system" data access in LiteDB.

Do you have idea about what king of IDiskService could be implement? A long time ago I implement SQL Server data layer for LiteDB.... instead of store in a filesystem, LiteDB store data in SQL server table... just for fun :)

**Comment by bbunderson** [comment]
@mbdavid you are correct. Sorry for the oversight. I don't really know what I was thinking.
