### ISSUE TITLE
"Field 'ExampleName$0$' has an invalid name" after upgrading to version 4.0

### ISSUE THREAD

**Issue by martinbu** [mbdavid/LiteDB#828]
After upgrading to LiteDB 4.0 my field names are not valid anymore. The reason for this is a change in  commit 0c69c84cc599c7001eba058791289b9c13bea082. From this commit on, the method IsValidFieldName in the BsonDocument class only allows the character '$' at index 0 in field names.

Is there any reason for this?

**Comment by mbdavid** [comment]
Hi @martinbu, sorry about that, but yes, in v4 its not possible field name starts with $. It because v4 use a new expression syntax for navigate on document (json-path). Json path always starts with `$`.

And, to simplify all decaration I append an `$.` if you path are not starts with `$`

Like:
In all version, you use: 
`Query.EQ("name", "john")`

In v4, to use json-path, you must write:
`Query.EQ("$.name", "john")`

But, to avoid re-write all queries, you can still write only `name` (not starts with `$`). Take a look here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Query/Query.cs#L281

**Comment by martinbu** [comment]
Thank your for your reply.
