### ISSUE TITLE
建议增加数据库文件的管理工具--from china

### ISSUE THREAD

**Issue by yuxin5156** [mbdavid/LiteDB#833]
建议增加数据库文件的管理工具--from china

**Comment by yuxin5156** [comment]
Suggest add a management tool

**Comment by yuxin5156** [comment]
best can view and can fool

**Comment by ddrrqq** [comment]
你在Kidding我？
LiteDB本身就是MongoDB Like的数据库，
作者本身也开发了非常好用的Litedb.Shell。
基本上和mongo.exe除了Brackets的区别，没区别。
find() = find

其它的插件别人也有开发：
图形界面预览工具：https://github.com/falahati/LiteDBViewer
图形界面编辑工具：https://github.com/JosefNemec/LiteDbExplorer

善于观察。

**Comment by mbdavid** [comment]
Olá pessoal, como foi dito, o LiteDB possui já possui uma ferramenta de shell que permite executar todos os comandos de manipulação de dados e alteração estrutural no banco de dados. É uma aplicação console simples, e os comandos podem ser vistos nesta pagina da wiki: https://github.com/mbdavid/LiteDB/wiki/Shell

😄

**Comment by xied75** [comment]
@yuxin5156 大家的回答如果满意，请关闭此issue. 如果不满意，请继续发言。

@mbdavid I see this is a great way of responding to foreign languages. 👍

**Comment by wai2dance** [comment]
建议作者建立一个中文学习的QQ群，，，，，
写一些Asp.Net Mvc 分别使用 【using (var db = new LiteRepository("xxx"))】  or  【using(var db = new LiteDatabase("xxx"))】  两种不同的 模式下的 成品 Demo.
官网的Demo感觉比较零散...

shell还没用过，最好能做一个简单点的，，，直接输入命令行，，表示那个有点困难..
C#小菜一枚，我的QQ是2360450496，刚使用这个数据库，求交流学习...

I was bad in English...
Suggest that the authors set up a Chinese learning of QQ group.
DBManageUI  good to Create a  chineses version.
Shell  i can't use very good! 
Enter the command line.
I feel a little difficult.
Best can make a similar to SQL Server Management Studio.
Can simple operation data directly.
If wrong, please understanding and forgive it.
Finally I hope I can get some Asp.NetMvc   【using (var db = new LiteRepository("xxx"))】  or  【using(var db = new LiteDatabase("xxx"))】  example of the finished project.Sample Zip File.Not a lot of not   understand file.
Contains paging data and relational query.

Because Examples of site now more fragmented.

Please......!Please teach me a lot. If i was not right (wr... forget how to ...)

My QQ number is 2360450496. 
Emial is 2360450496@qq.com

**Comment by wai2dance** [comment]
show my LiteDB ASP.Net Mvc 

[http://ogiw0i9ef.bkt.clouddn.com/ssss3.png](url)

Is still in development.Read speed is good.

**Comment by xied75** [comment]
@wai2dance 作者是巴西人，说葡萄牙语，英语也是他的第二语言。他不大可能使用QQ或者微信，更加不大可能开群。目前这个项目有Gitter上的讨论群，不知你是否使用Gitter。

作者可能无法兼顾很多非英语用户的需求，这方面也许我们可以自助一下，征得他的同意话，我们可以在国内的知名网站例如coding.net上做一个中文镜像，来专注于服务中文用户。

**Comment by mbdavid** [comment]
大家好，很高兴知道LiteDB有来自巴西的用户。 你必须想象，我不能理解中文里至少有一个单词。
@lidanger用户是中国第一批接触和创建自述文件的中国用户之一。 这个库在这里非常活跃，并且很好的了解LiteDB。 它可能是一个想要贡献的人。
如果您创建了一些关于LiteDB的内容，请将链接发给我，以便我可以在README官方中透露这些内容，从而增加社区。

拥抱

（这个文本已经被Google完全翻译了，也就是说我不负责翻译中可能写的东西） 😄 

https://github.com/lidanger/LiteDB.wiki_Translation_zh-cn

**Comment by ddrrqq** [comment]
Wow, China is 03:00 now.
I getting these replay emails more times XD
Sometimes I feel ashamed that I’m a Chinese～～
I've been recommending LiteDB to my programmer friends.
Every times it is Kick Ass Very Nice！XD
So Good luck & I Love You！

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
