### ISSUE TITLE
No way to change LiteCollection type

### ISSUE THREAD

**Issue by Dessix** [mbdavid/LiteDB#85]
Previously, I would use LiteCollection.Database to get the same named collection with a different type, but this accessor has been removed in the 2.0.0 beta. The behavior itself was used for passing a collection without knowing the particular type to be stored *within* said collection. I assume this would be a "be sure this is safe" sort of thing, but it would be equivalent to casting, after all. Any ideas of what to do instead (without passing the full database), or can such a feature be added?

**Comment by mbdavid** [comment]
Hi @Dessix, I didn't undestand why you could get same collection with diferent type. LiteCollection.Database was the same reference of initial LiteDatabase instance. Now, in v2, LiteCollection doesnt need LiteDatabase anymore, because uses only DbEngine (a new low layer of database). In DbEngine there is not strong type entity classes, only `BsonDocument`. But you can still use:

```
var db = new LiteDatabase("...");
var col1 = db.GetCollection<Customer>("customer");
var col2 = db.GetCollection<Person>("customer");
var col3 = db.GetCollection("customer"); // same as GetCollection<BsonDocument>()
...
```

**Comment by a44281071** [comment]
I think something about LiteDB:
1. this is based mongodb, and more simple, but we use it efficient.
2. BsonDocument, it has dynamic schema, like mongodb, but not like C#, it must have a choose: "I use this in Strongly Typed Language". But not: "First, I can use it by BsonDocument". So it's more importan to achieve Strongly Type in same document.
3. Sorry for chaos of language. I think mongodb use field "_type" for strongly type, like field "_id".
thanks...
