### ISSUE TITLE
index from mapper

### ISSUE THREAD

**Issue by Jacknq** [mbdavid/LiteDB#863]
hi, in  v4 against v3
where did the index method go from.mapper entity object?
this was practical to have it by schema definition.
  it would be cool feature if would be mapped automatically from mapper, since mapping is always coming by db initialization.

**Comment by mbdavid** [comment]
Hi @Jack85, when I remove this from mapper my idea was separate concerts that make BsonMapper be only an POCO <-> BsonDocument, just because LiteEngine "see" only BsonDocument. Also, using index definition before a query I always need run "EnsureIndex".

It's not in my plans for now just add this back to BsonMapper. But I'm re-writing a large part of LiteDB (to v5) and I will think a centralized way to map database classes better than actual BsonMapper.

**Comment by Jack85** [comment]
ok,  but its kind of logical there, to avoid creating collections by db init again, trying to avoid of repeating code once you have collection, getting it again. In my use cases im creating index very often than just dropping if at all, this is frequent stuff if you want performance. maybe it could be solved with some injection. 

happy to see that v5. good work.

**Comment by xied75** [comment]
It would be great to have a central place to set Indexes, or, call a bunch of EnsureIndex(..)

Otherwise if in separate classes/files we init the Db, we always need to remember to call db.EnsureIndex, which is easy to forget.

If we don't want this to be burdened onto Mapper, we could create another Global thing to hold this.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
