### ISSUE TITLE
db.xxx.select - High Memory Load 

### ISSUE THREAD

**Issue by malt001** [mbdavid/LiteDB#865]
Hello,

we are using your solution to store a large set of objects with many properties on a web server.
But since the db file grow up to ~800MB we are facing enormous memory load issues when accessing the data (up th 3GB memory while reading 2000 records of the data).
For example we need to get a subset of the Product called ProductLite (simplified classes)

```
        public class ProductLite
        {
            public string Name { get; set; }
            public Guid Guid { get; set; }
        }

        public class Product
        {
            public long Id { get; set; }
            public string Name { get; set; }
            public string Number { get; set; }
            public Guid Guid { get; set; }
            public Details DetailList { get; set; }
        }

        public class Details
        {
            public int Id { get; set; }
            public Dictionary<int,string> Values { get; set; }
        }
```
The best method we have found so far is the following

```
var lites = db.ExecuteRawQuery<ProductLite>("db.Product.select $.Name, $.Guid");

public IEnumerable<T> ExecuteRawQuery<T>(string query)
{
     var items = _database.Engine.Run(query).Select(x => x.AsDocument);
     return items.Select(item => BsonMapper.Global.ToObject<T>(item));
}
```
But still 2,5GB memory while reading.
So the question is: what is the desired way to get the data without burning down the servers memory when 3 users access the database? 

Best regards

**Comment by mbdavid** [comment]
Hi @malt001, `Run` method is not your best friend in this case. All documents are stored in memory until you get your first document (Run method return an List not an IEnumerable). In this case, the best solution is:

```
var docs = _database.Engine.Find("Product", Query.All());
var items = docs.Select(x => BsonMapper.Global.ToObject<T>(x))

return items; // will return an IEnumerable - do not run "ToList()", consume each item in a loop
```

Tell me if works

**Comment by malt001** [comment]
Hello @mbdavid - wow - this was a fast response. THX! The updated code uses about 400-600MB memory now - so absolutely a great deal for a 2 line change 👍 

Maybe you have another idea for the duration it runs:
Given 2000 records and objects with 10 different properties it takes about 15-20 seconds to create the "sub"objects with only 2 properties - in the final solution we talk about 100000 records and I feel this will drive us into problems. I guess this could be optimized by tweaking the BsonMapper behavior, but I can't figure out how to dive into this. Any hint would be great!

**Comment by mbdavid** [comment]
Hi @malt001, the success key in any document database is keep document small as possible with minimal updates. Each update always need load all document (read pages and deserialize data), change your data and serialize/persist again. There is no "single property update" because BSON format need to be always all-read, all-write.

I don't know well you data model and how you will use, but if you have an document with an embedded document that are too big (like an array with many sub-documents) you need split in 2 collections (like an relational database).  In LiteDB you can use `Includes` and `DbRef` to work "like" an relational.

On example is how `FileStorage` store each file: 1 collection store file name and another collection store chunks of each file. LiteDB use same idea from MongoDB:

https://docs.mongodb.com/manual/core/gridfs/

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
