### ISSUE TITLE
How to do replacing BeginTrans statements in 3.1->4.x upgrade?

### ISSUE THREAD

**Issue by bars137** [mbdavid/LiteDB#866]
Hello,
I currently used litedb version 3.1.4 with my project, want to upgrade latest version of litedb, but i cannot find the solutions of replacing the code with BeginTrans() code like followings:
```c#
// db update
using (var trans = DB.BeginTrans())
{
    // add new product information
    ProductInfo failProductInfo = new ProductInfo
    {
        ID = LiteDB.ObjectId.NewObjectId(),
        WorkID = CurrentWork.WorkID,
        ContainerID = -1,
        ContainerIndex = -1,
        InTime = DateTime.Now,
        Result2 = InspResult.Fail,
        Code2 = failString,
        Data2 = null
    };

    DB.ProductInfoCollection.Upsert(failProductInfo);
    trans.Commit();
}
```
now my program have many individual threads (8 threads), each thread controls own measuring instrument, update or insert information when completing instrument test.
In 3.1.4 version, i used transaction for concurrent record handling, but transaction was removed latest version. I want to upgrade the library but cannot do because this problem.
Can it be replaced to simple lock statement, or need some another way?
If anyone knows the solutions, please give a way how to replace BeginTrans statement or some helps.
Thanks.

**Comment by mbdavid** [comment]
Hi @bars137,

In you example, transaction are used only for lock database, because you are inserting a single document only. If you need lock database just to fill you `ProductInfo` class, I recommend you use a simple `lock` .NET statement (over `LiteDatabase` instance).

LiteDB v4 support concurrent insert - locks are made internally and each write operation are serialized. So, if you don't need fill your class in a safe thread, just do a simple insert.

**Comment by bars137** [comment]
Hello @mbdavid , I tested the code just remove BeginTrans statements, and it works well.
No problems to insert, update, upsert action with version 4.1.1.
Thanks for your support. I will close this issue.
