### ISSUE TITLE
When will we get ver 5 beta or alpha? also will you ever open a discord?

### ISSUE THREAD

**Issue by Moar-Chan** [mbdavid/LiteDB#869]
I just want to try out ver 5 of the lib and A discord would be nice for more general talking.

**Comment by Moar-Chan** [comment]
How do i assign issue as question?

**Comment by mbdavid** [comment]
Hi @Moar-Chan, I had a Label called "question" but I don't use too much.

About v5, no idea yet about beta - It's just because I didn't know well all thinks that I want implement in this new version.

Sometimes it's hard  to know what people expect from a native embedded database and what is possible (for me) develop. I want create a twitter poll about some features that sound nice to me but I know well if anyone want this.

But tell me, what you read about v5 that make you question this?

**Comment by Moar-Chan** [comment]
I just thought about general speed but also the db .exe thing might be cool.

**Comment by JensSchadron** [comment]
@Moar-Chan Wanted to let you know that v5 will be released in the very near future (if no issues come up). The labels can sadly only be assigned by david (and myself since a week). I'll close this issue as well as I'm doing some cleaning in the issue list. If you've some more questions, you can also let us know something through the gitter (link in the README) or create another issue.
