### ISSUE TITLE
The proper way to autoincrement after app restart

### ISSUE THREAD

**Issue by MihaMarkic** [mbdavid/LiteDB#887]
I'm noticing that autoincrement works only while app runs, but it will loose track on restart.
So how does one handle properly app restarts regarding autoincrement(both ObjectId and i.e. int)?

**Comment by mbdavid** [comment]
Hi @MihaMarkic,

`ObjectId` are sequential based on DateTime on application starts. Each start reset this number but still sequential.
`Int32` are sequential based on collection sequence (is a internal variable for each collection). Each insert increment this value. There is no problem with reset app, because this sequence number are stored inside database.

Both number are not resettable. If you need a resettable counter, you need create your own control (eg: using another collection with `last_id`)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
