### ISSUE TITLE
our/own Advices

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#917]
hello @mbdavid 
LiteDB is so optimum and lite
but when we decided to use that then try to see how that working in clients and servers
at first working so good but after more working may have some problems
we saw your database engine and just have some proposals

first better change your mind about pages, pages must be in split files
-this is because that cant handle much indexes in more tables
you cant push indexes for ever
-this is also because your data may not be fragmentary and need defragment

second  split database interface and database engine
its may not be important now 
but when LiteDB Project gets bigger you must declare new query for every new idea
database interface and database engine seems split but not actually, 
engine working directly on a file but interface try to make query for engine
lesson, your engine is strongly good but engine must just contain insert,Update,Delete,GetData

Third get data page constant length
this is like Partitioning on disk
you may say why, because if database was full then we know what must do
i talking about shrink function

tnx for reading and i will be happy if i talking directly to you

**Comment by mbdavid** [comment]
Hi  @miladsadeghi72, thanks to share your ideas and your thoughts about LiteDB

About database multi pages/files - The main idea is keep as embedded database and use just a single file to store all data. Store and indexed. That's why I always prefer use single file. Some databases has diferente files for data and index, others are only one file to data and index (like sql server). But one file per page is too much files and hard to work in concurrency mode - all databases just "ignore" filesystem and create own filesystem to manage data as needed. LiteDB do the same. Using my own "filesystem" and just do all fine tunning to read/write data to my specific way.

In next version of LiteDB this split about database/engine will be more clear. But today, I already has some "storage engine" conecepts only in `LiteEngine` class... and database class access uses LiteDatabase. Next version I will work with 2 namespaces: LiteDB.Engine with all classes for engine-only and LiteDB for database "client" access (with support for local database or remote ones).
Also BsonExpressions will me more complex to support to better query syntax and best index selection options. But storage engine do more than CRUD - create and analyze indexes, create/commit and rollback transactions, parse string expressions, shrink datafiles, ...
