### ISSUE TITLE
.Include()

### ISSUE THREAD

**Issue by alfcas** [mbdavid/LiteDB#937]
LiteDB document search is:

public List<My.Car> CarsFilter(Expression<Func<My.Car, bool>> predicate)
{
        List<My.Car> cars = new List<My.Car>();
        using (var dbcontext = new My.LiteDBContext(p_dbfile))
        {
             cars = dbcontext.Cars
                             .Include(s => s.Driver)
                             .Include(s => s.Equipment)
                             .Find(predicate)
                             .ToList<My.Car>();
        }
       return cars;
}

predicate is:

public Expression<Func<My.Car, bool>> DriverName(Expression<Func<My.Car, bool>> predicate, string arg1, string arg2)
{
//...
//...
  return predicate.And( s => s.Driver.DriverName.StartsWith( arg1 ));
}

Find() doesn't work because "Driver" is empty at .Find() time, how to deal with?

**Comment by mbdavid** [comment]
Hi @alfcas, this occurs because Includes are executed before filter and you are trying filter based on an include. Current v4 do not support this "include before" as I'm implementing in v5. You have 2 options:
- Create an index in Car collection with DriverName (super fast way)
```
dbcontext.Cars.EnsureIndex("driverName", "$.Driver.Name")

cars = dbcontext.Cars
.Include(s => s.Driver)
.Include(s => s.Equipment)
.Find(Query.StartsWith("driverName", arg1)
.ToList<My.Car>();
```

Or be more dynamic and run incude before query (and use Linq where)

```
cars = dbcontext.Cars
.Include(s => s.Driver)
.Include(s => s.Equipment)
.FindAll()
.Where(predicate)
.ToList<My.Car>();
```

**Comment by alfcas** [comment]
thank you, I do a try ;-)

**Comment by a-a-k** [comment]
Hi @mbdavid!

Please take a look and help me to figure out. I have two entityes `Cars` and `Tyres`, `Cars` has a field refs on `Tyres`. Now I'm trying take data by two ways
first returns nothing
```
                var cars = db.GetCollection<Cars>(nameof(Cars))
                    .Include(i => i.Tyre);
                var tyres = cars
                    .Find(m =>
                        (m.Tyre.FrontAxleWidth == cache.Width &&
                         m.Tyre.FrontAxleHeight == cache.Height &&
                         m.Tyre.FrontAxleDiameter == cache.Diameter) ||
                        (m.Tyre.RearAxleWidth == cache.Width &&
                         m.Tyre.RearAxleHeight == cache.Height &&
                         m.Tyre.RearAxleDiameter == cache.Diameter))
                    .ToList();
```
but second works like a charm
```
var cars = db.GetCollection<Cars>(nameof(Cars))
                    .Include(i => i.Tyre);
                var res = cars
                    .Find(m =>
                        m.Mark == cache.Mark &&
                        m.Model == cache.Model &&
                        m.YearStart <= cache.Year &&
                        m.YearEnd >= cache.Year)
                    .ToList();
```
I think this is because in the first case we ask for ref entity, isn't it? Could you explain that behaviour? Thanks.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
