### ISSUE TITLE
ASP.NET application pool recycling and concurrency

### ISSUE THREAD

**Issue by Enichan** [mbdavid/LiteDB#950]
In the documentation for concurrency this is written:

> If your application works in a single process (like mobile apps, asp.net websites) prefer use a single database instance and share across all threads.

For an ASP.NET it's true __most of the time__ that there's only a single process active, but an application pool could recycle either periodically, because a memory, request, limit has been reached, or because certain changes have happened to a web application (bin files changed, etc). When this happens the current process is able to finish its current requests but a new one is started.

Wouldn't this mean that rarely it's possible for an ASP.NET application to have concurrent use of the database from multiple processes, which means you should specify 'Mode=Shared' instead of 'Mode=Exclusive' in the connection string?

**Comment by mbdavid** [comment]
Hi @Enichan, I never thought about this time when application pool recycle... but, during this recycle it's possible has 2 instances of ASP.NET context?

If happening, must be changed to shared mode - BUT, in this case, I still think that could be better do some "lock" system for this short time. Just becase Exclusive mode is faster than shared, because shared always must check/re-checks changes in every data access. This is so complicated that in v5 will be available only Exclusive mode (shared mode will be accepted only using NamedPipes and server instance)

**Comment by Enichan** [comment]
Glad to hear I'm not insane. :) If you're removing shared mode will you add something like the code below so those of us who rely on it can easily implement the locking ourselves?

```csharp
using (var dbLock = database.SharedLock()) {
    // operations go here
}

**Comment by mbdavid** [comment]
Next version will try open file for 1 minute (it's timeout parameter) if are locked by another process....

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
