### ISSUE TITLE
Browse database on a mac

### ISSUE THREAD

**Issue by rasmuschristensen** [mbdavid/LiteDB#955]
Hello,

Is there any recommendation for an osx supported tool to view the data stored in the database file? I've only been able to find windows tools

**Comment by mbdavid** [comment]
Hi @rasmuschristensen, you can try compile shell tool using .net core. If works, tell me than I can add as solution for this.

**Comment by vorou** [comment]
It compiles & works without any tweaks under Mono in MacOS.

Won't compile under Core as is, since you target both Framework and Standard. As far as I understood, there's no need to target Framework, unless there is an API which exists in Framework only.

**Comment by rhullah** [comment]
I've also pulled it down and have gotten it to compile on MacOS.  Although I was able to get it to compile with .net core (not using Mono).  All I needed to do to LiteDB.Shell.csproj was either change the `<TargetFramework>` to `netcoreapp2.1` or add [conditional target frameworks](https://weblog.west-wind.com/posts/2017/Sep/18/Conditional-TargetFrameworks-for-MultiTargeted-NET-SDK-Projects-on-CrossPlatform-Builds#Conditional-TargetFrameworks).

Then I was able to publish it to an executable with the following:
`dotnet publish -c Release -r osx-x64 -f netcoreapp2.1`

I agree also that the Shell doesn't need to target net40 as nothing it uses depends on the full framework. So having it only target `netcoreapp*` should work for all systems.

**Comment by mbdavid** [comment]
Hi @rhullah, do you want create an PR about this? Will be great and I can test it here.

**Comment by rhullah** [comment]
@mbdavid,

I finally had time to push a PR with the edits allowing the Shell to be ran on MacOS.

**Comment by mbdavid** [comment]
About shell tool in non-windows environment: in v5 I already made a new tool, LiteDB.Studio, with much more resources to view/edit/analyze database and new SQL language to manipulate data.

![litedb studio_01](https://user-images.githubusercontent.com/1137197/42338617-be5b0250-8060-11e8-9354-f0e28fa2a1a8.png)

But, this tool was made in WinForms, which are not compatible with .netcore (at least now). And now? Should I keep maintain shell tool (using this new SQL syntax) or wait for WinForm be compatible with other platforms?

**Comment by rhullah** [comment]
Yeah, I was reading you v5 branch and all your changes sounds really exciting.  I noticed the screen shots of the Browser which would be awesome cross platform.  It's a tough question you ask because there doesn't seem to be a single answer.  The most obvious one to me would seem to be a Xamarin App.  But then there's also a few 3rd party solutions.  I personally haven't found what I would consider a great solution, which is why I was looking to get the Shell working on Mac.  So personally, I'd say stick with the Shell for now and add the SQL syntax.  Maybe something in the future will lead the way in this?

For your own reading, here's a couple 3rd party solutions for .NET cross platform UI:

- [Eto.Forms](https://github.com/picoe/Eto)
- [Avalonia UI](http://avaloniaui.net/)
- [Mono GUI Toolkits](http://www.mono-project.com/docs/gui/)

**Comment by JensSchadron** [comment]
I'm thinking of porting the current LiteDB Studio to mac, but it might take quite some time.

**Comment by JensSchadron** [comment]
See issue #1278

**Comment by winsonet** [comment]
so, may I know whether has a tool can browse LiteDB on a Mac now?
thanks!

**Comment by JensSchadron** [comment]
@winsonet I started working on a client somewhere in a august, but due to lack of time, I had to put it on-hold. So for now, there isn't a client for Mac as far as I know.

**Comment by iliaga** [comment]
any news on this one ?

**Comment by namigop** [comment]
I built one for myself and open sourced it. It's cross-platform and works on MacOS, Windows and Linux

Please try out OneBella : [https://github.com/namigop/OneBella](https://github.com/namigop/OneBella )

**Comment by koliyo** [comment]
Wow, thank you! @namigop 🙏
