### ISSUE TITLE
Bugs in v5.

### ISSUE THREAD

**Issue by QRobberDK** [mbdavid/LiteDB#998]
Hi Mauricio.

We have been looking a lot on your v5 branch and we are aware that it's a beta version and therefore not stable, but I'm still asking if you have an estimate on when there will be a stable version of v5?

Best regards
Michael Robdrup
Qualiware

**Comment by mbdavid** [comment]
Hi @QRobberDK, thanks for your interesting in LiteDB. The new v5 version will not be only an upgrade version from v4, but a complete re-write of LiteDB. This new version uses lot of new features and need create a much more complex structure. Also, LiteDB v5 will not only for embedded apps but will be access via TCP/NamedPipe (with server version). With this, LiteDB will support not only .NET but can be used in any other platform/language.
Current version are in still in complete dev and not work at all. I'm changing almost every day to get best code and performance... and I use 2 computer (home and work), so sometime I commit in github only to access in another one (with not compiling code).
I'm dedication this all this year for this new version... and my plans are release in end of 2018 a stable version of LiteDB.
I will release, in 2 or 3 months the first beta of engine-only database for first public tests.

**Comment by AwsomeCode** [comment]
Hi @mbdavid, is it possible that you can manage to add transaction in 4v it would be nice.

**Comment by mbdavid** [comment]
Hi @AwsomeCode, unfortunately is not easy to implement this. When I wrote v4 i removed lots of parts that implement transaction (from v3).

If you can wait, new v5 will be fully support for transaction with snapshot version control and a new window admin UI  😄 

![image](https://user-images.githubusercontent.com/1137197/41426248-7350dc7c-6fd9-11e8-9f1f-af2b71f28006.png)

**Comment by AwsomeCode** [comment]
Oh! this looks nice. Sure I can wait, currently I am using SQLite. As soon as v5 beta comes out I will start testing it out.

**Comment by tjmoore** [comment]
Still on 2.04 and been holding off due to lack of transaction support. Although I've had to drop a lot of use of transactions where I can get away with it or work around.

Is v4 considered stable now, and what's the upgrade path from 2.04? Code and more importantly upgrading our customer's database files.

**Comment by jboada** [comment]
Hi @mbdavid 

As i can see, your project is getting bigger, congratulations about it.

After reading this part 

> Also, LiteDB v5 will not only for embedded apps but will be access via TCP/NamedPipe (with server version)

 , a serer version, very intersting

Please, add transactions in this version, sometime business logic requires "all or nothing" to be right and avoid corrupted data.

**Comment by mbdavid** [comment]
Hi @jboada, yes, transactions are back in v5. Actually, all v5 was around this... write ahead log (WAL) for transaction support.

The server version will not be available at first time because I spend lot of time (much more than I expected) fixing and improving query performance (with support a new SQL language)... so, some features will be delivery later.

**Comment by wilberolive** [comment]
How is the first release of v5 progressing?

I have to start a new project I and would like to use LiteDB, but not sure if I should start with v4 or if I should hold out for the first release of v5 if it is close?

If I start with v4, will it be an easy upgrade to v5 or will there be many changes that I would have to make?

**Comment by mbdavid** [comment]
Hi @wilberolive, v5 will still under dev because I'm  complete change storage engine to get great performance improvement. Current v5 are not as fast as I wanted... and I made bad decisions about `BinaryReader` and `BinaryWriter`. I'm fixing this in a new branch.

But you can starts with v4 and migrate after to v5.. API change will be minimal. Datafile format will change too, but I already made import/convert from old version.

**Comment by wilberolive** [comment]
Thanks for your reply.

Will the data file upgrade from v4 to v5 be an automated process when connecting to the data file for the first time with v5 or is it a manual process? I ask because I have hundreds of clients each with their own v4 data file. I cannot upgrade the data files for everyone manually. So would like a way to do it automatically via code?

**Comment by mbdavid** [comment]
This migration will run at first time open database in v5 (with old-version backup support).

**Comment by jboada** [comment]
This new version with transactions will be nice and this automatic upgrade
version makes it look amazing!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
